docker/docker-ce

components/engine/daemon/prune.go
Signed-off-by: Alfred Landrum <alfred.landrum@docker.com>
(cherry picked from commit 32da2a4234c5c68ff466dc1afc91ba98dbbe199a)
-- 
Cherry-pick of moby/moby#33409
=> prevent image prune panic

components/engine/plugin/backend_linux.go
This was mistakenly unmounting everything under `plugins/*` instead of
just `plugins/<id>/*` anytime a plugin is removed.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit db5f31732a9868c1e9e4f9a49be70b794ff82d4f)
-- 
Cherry pick of moby/moby#33422
=> Don't unmount entire plugin manager tree on remove

components/engine/vendor.conf, components/engine/vendor/github.com/Microsoft/go-winio/pipe.go, components/engine/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Signed-off-by: Darren Stahl <darst@microsoft.com>
(cherry picked from commit 3f13107223a9753d709c196c46f1c846041fc0c3)
-- 
Cherry-picked from moby/moby#33365
Conflict in `vendor.conf`, the local version was `0.4.0` instead of the expected `0.4.1`
=> Update go-winio to v0.4.2

components/engine/pkg/devicemapper/devmapper.go
DeviceMapper tasks in go use SetFinalizer to clean up C construct
counterparts in the C LVM library.  While thats well and good, it relies
heavily on the exact interpretation of when the golang garbage collector
determines that an object is unreachable is subject to reclaimation.
While common sense would assert that for stack variables (which these DM
tasks always are), are unreachable when the stack frame in which they
are declared returns, thats not the case.  According to this:
https://golang.org/pkg/runtime/#SetFinalizer
The garbage collector decides that, if a function calls into a
systemcall (which task.run() always will in LVM), and there are no
subsequent references to the task variable within that stack frame, then
it can be reclaimed.  Those conditions are met in several …
=> Ensure that a device mapper task is referenced until task is complete

components/cli/cli/command/registry.go, components/cli/cli/command/registry_test.go
The current implementation of the ElectAuthServer doesn't handle well when the
default Registry server is not included in the response from the daemon Info
endpoint.
That leads to the storage and usage of the credentials for the default registry
(`https://index.docker.io/v1/`) under an empty string on the client config file.
Sample config file after a login via a Docker Daemon without Registry
information:
```json
{
"auths": {
"": {
"auth": "***"
}
}
}
```
That can lead to duplication of the password for the default registry and
authentication failures against the default registry if a pull/push is performed
without first authenticating via the misbehaving daemon.
Also, changes the output of the warning message from stdout to sdterr as
per dnephin suggestion.
Signed-off-by: Marcus Martins …
=> Handle a Docker daemon without registry info

components/engine/builder/dockerfile/builder.go, components/engine/builder/dockerfile/dispatchers.go, components/engine/integration-cli/cli/build/fakecontext/context.go, components/engine/integration-cli/docker_api_build_test.go
the source was missing from the second dispatch
Signed-off-by: Daniel Nephin <dnephin@docker.com>
(cherry picked from commit 3f2604157790408acf5ad05c74cebe105f2b6979)
--- 
Cherry pick of moby/moby#33500
=> Fix ONBUILD COPY

components/engine/daemon/cluster/executor/container/container.go, components/engine/integration-cli/docker_cli_service_create_test.go
Cherry-picked from: https://github.com/moby/moby/pull/33578
If a service alias is copied to task, then the DNS resolution on the
service name will resolve to service VIP and all of Task-IPs and that
will break the concept of vip based load-balancing resulting in all the
dns-rr caching issues.
This is a regression introduced in #33130
Signed-off-by: Madhu Venugopal <madhu@docker.com>
(cherry picked from commit 38c15531501578b96d34be5ce7f33a0be6be078f)
=> Service alias should not be copied to task alias

components/cli/cli/command/service/parse.go
Cherry-picked from docker/cli#162
If configs are declared for a service and pointing on an old
daemon, error out properly (instead of "page not found").
If there is no configs declared, don't call convertServiceConfigObjs
to avoid having an error.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
(cherry picked from commit cf5550c4260bcea0f733c7abfc6bdf0188357eea)
=> Handle case of configs on old daemon

components/cli/vendor.conf, components/cli/vendor/github.com/docker/docker/pkg/term/termios_bsd.go, components/engine/pkg/term/termios_bsd.go
To address https://github.com/moby/moby/issues/33101 will revert the changes originally put in with https://github.com/docker/docker-ce/pull/25
Similar revert was performed upstream in https://github.com/docker/cli/pull/166 and https://github.com/moby/moby/pull/33577
=> revert Set OPOST on bsd

components/engine/libcontainerd/remote_unix.go
Cherry-picked from: moby/moby#33419
It has observed defunct containerd processes accumulating over
time while dockerd was permanently failing to restart containerd.
Due to a bug in the runContainerdDaemon() function, dockerd does not clean up
its child process if containerd already exits very soon after the (re)start.
The reproducer and analysis below comes from docker 1.12.x but bug
still applies on latest master.
- from libcontainerd/remote_linux.go:
329 func (r *remote) runContainerdDaemon() error {
:
:      // start the containerd child process
:
403     if err := cmd.Start(); err != nil {
404             return err
405     }
:
:      // If containerd exits very soon after (re)start, it is
possible
:      // that containerd is already in defunct state at the time
when
:      // …
=> libcontainerd: fix reaper goroutine position

components/engine/client/service_create.go, components/engine/client/service_create_test.go, components/engine/client/service_update.go
---
Cherry pick of moby/moby#33279 which fixed docker/cli#79 (AKA docker service ls/ps is not truncating digests anymore)
=> Ensure service images get default tag and print familiar strings

components/cli/vendor.conf, components/cli/vendor/github.com/docker/docker/client/service_create.go, components/cli/vendor/github.com/docker/docker/client/service_update.go, components/engine/integration-cli/docker_cli_service_logs_test.go, components/engine/integration-cli/docker_cli_swarm_unix_test.go
Cherry picking https://github.com/moby/moby/pull/33279 into `components/cli/vendor/github.com/docker/docker`.
This is related to the changes in https://github.com/docker/docker-ce/pull/13
cc @andrewhsu @mlaventure @thaJeztah
=> [cherry-pick] vendor: Ensure service images get default tag and print familiar strings

components/cli/cli/command/stack/deploy.go, components/cli/cli/command/stack/deploy_bundlefile.go, components/cli/cli/command/stack/deploy_composefile.go, components/cli/cli/compose/convert/service.go, components/engine/hack/integration-cli-on-swarm/host/dockercmd.go, components/engine/integration-cli/docker_cli_stack_test.go
This PR cherry-picks the two commits from https://github.com/docker/cli/pull/121. It is required to avoid a digest-pinning regression for `docker stack deploy`.
It enables digest pinning for `docker stack deploy`, and adds a `--resolve-image` flag to `stack deploy` to provide options to control it.
Some of the refactoring from https://github.com/docker/cli/pull/145 that came earlier doesn't show up in this cherry-pick, but I've tried to make sure the changes here don't cause problems, since https://github.com/docker/cli/pull/121 is based on top of https://github.com/docker/cli/pull/145 (cc @dnephin)
Tests might fail right now, I'll add a commit to fix them. In particular, changes from https://github.com/moby/moby/pull/33386 are what will be needed.
cc @andrewhsu
=> [cherry-pick] Enable client side digest pinning for stack deploy

components/cli/cli/command/service/update.go
Cherry-picked from: docker/cli#144
Commit 78c204ef798c7380e11ba26e5cd231e04fc6efe4 added
(f9bd8ec8b268581f93095c5a80679f0a8ff498bf in the moby repo)
a validation to prevent `--rollback` from being used
in combination with other flags that update the
service spec.
This validation was not taking into account that
some flags only affect the CLI behavior, and
are okay to be used when rolling back.
This patch updates the validation, and adds
`--quiet` and `--detach` to the list of allowed
flags.
(cherry picked from commit f10f29df8d7ffede3faa29120a06c199e52a1d0c)
=> Allow --detach and --quiet flags when using --rollback

components/engine/pkg/plugins/client.go, components/engine/pkg/plugins/client_test.go
Cherry-picked from: moby/moby#33413
Closes: #33412
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>
(cherry picked from commit 62871ef2fa52b0a2e426c30f36d35a9ba1e92fac)
=> Do not reuse a http.Request after a failure in callWithRetry

components/engine/daemon/kill.go, components/engine/integration-cli/docker_api_containers_test.go
Cherry-picked from: moby/moby#33335
This fixes an issue where if a stop signal is set, and a user sends
SIGKILL, `container.ExitOnNext()` is not set, thus causing the container
to restart.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit 114652ab86609e5c0cbfad84f642942b466a0596)
=> Check signal is unset before using user stopsignal

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/ca/certificates.go, components/engine/vendor/github.com/docker/swarmkit/ca/config.go, components/engine/vendor/github.com/docker/swarmkit/ca/renewer.go, components/engine/vendor/github.com/docker/swarmkit/ca/server.go, components/engine/vendor/github.com/docker/swarmkit/manager/allocator/network.go, components/engine/vendor/github.com/docker/swarmkit/manager/allocator/networkallocator/drivers_darwin.go, components/engine/vendor/github.com/docker/swarmkit/manager/manager.go, components/engine/vendor/github.com/docker/swarmkit/node/node.go
To get the changes:
* docker/swarmkit#2234 [ca] Validate the Root CA certificate before updating the security config
* docker/swarmkit#2237 allocator: Avoid assigning duplicate IPs during initialization
* docker/swarmkit#2238 [ca/node] Maybe update the root CA when renewing the TLS cert
The changes between the two commit hashes on docker/swarmkit repo:
https://github.com/docker/swarmkit/compare/758b59114f7eef55faca7007af773d4097540ed2...6083c7689ed00a6f2d67941443603df69c2ff6ba
=> revendor github.com/docker/swarmkit to ef3c57a

components/engine/cmd/dockerd/daemon.go, components/engine/cmd/dockerd/daemon_unix_test.go, components/engine/contrib/completion/zsh/_docker, components/engine/docs/deprecated.md, components/engine/docs/reference/commandline/dockerd.md, components/engine/integration-cli/docker_cli_logout_test.go, components/engine/integration-cli/docker_cli_pull_test.go, components/engine/integration-cli/docker_cli_registry_user_agent_test.go, components/engine/integration-cli/docker_cli_v2_only_test.go, components/engine/man/dockerd.8.md, components/engine/registry/config_unix.go
Cherry-picking change: https://github.com/moby/moby/pull/33629
Deprecation of interacting with v1 registries was started in docker 1.8.3, which added a --disable-legacy-registry flag.
This option was announced to be the default starting with docker 17.06, and v1 registries completely removed in docker 17.12.
This patch updates the default, and disables interaction with v1 registres by default.
=> cherry-pick: Disable legacy (v1) registries by default

CHANGELOG.md
---
Missing entry/entries for https://github.com/docker/docker-ce/pull/55 (cc @mavenugo) and potentially https://github.com/docker/docker-ce/pull/43 (cc @cyli)
=> Update changelog for 17.06.0-ce-rc3

components/engine/container/stream/attach.go, components/engine/pkg/pools/pools.go, components/engine/pkg/pools/pools_test.go
Cherry-pick the commits from:
* moby/moby#33472 container/stream/attach: use pools.Copy
To fix:
* moby/moby#32711 Dockerd eats 20GB of RAM
=> cherry-pick container/stream/attach: use pools.Copy

components/cli/cli/command/stack/client_test.go, components/cli/cli/command/stack/remove.go
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
(cherry picked from commit 2128b3f11208197c8d0340ac22cd4ff9d36b96cc)
From docker/cli#182
=> Do not call the config endpoint if API is lower than 1.30

CONTRIBUTING.md
Add a link to the docker/docker-ce-packaging repo so others could contribute at the right place.
=> Add link to docker-ce-packaging repo

components/cli/cli/command/service/progress/progress.go
Backport fix:
* docker/cli/pull/237 progress: Show progress of replicated tasks before they are assigned
=> [17.06] progress: Show progress of replicated tasks before they are assigned

components/engine/integration-cli/docker_cli_daemon_test.go, components/engine/plugin/backend_linux.go, components/engine/plugin/manager.go, components/engine/plugin/manager_linux.go
Backport fixes:
* moby/moby#33830 Make plugin removes more resilient to failure
* moby/moby#33944 Fix plugin remove dir name after rename.
=> [17.06] Make plugin removes more resilient to failure

components/engine/libcontainerd/remote_unix.go
Backport fix:
* moby/moby/pull/33483 Limit max backoff delay to 2 seconds for GRPC connection
=> [17.06] Limit max backoff delay to 2 seconds for GRPC connection

components/engine/daemon/logger/jsonfilelog/jsonfilelog.go, components/engine/daemon/logger/jsonfilelog/read.go
Backport fix:
* moby/moby/pull/33897 Fix log readers can block writes indefinitely
The only conflict was in the `components/engine/daemon/logger/jsonfilelog/read.go` file:
```
if config.Tail != 0 {
<<<<<<< HEAD
tailer := ioutils.MultiReadSeeker(append(files, latestFile)...)
=======
tailer := multireader.MultiReadSeeker(append(files, latestChunk)...)
>>>>>>> e2209185ed... Fix log readers can block writes indefinitely
tailFile(tailer, logWatcher, config.Tail, config.Since)
}
```
@cpuguy83 Because moby/moby@2445e6b moved multireader. I decided to go with the `ioutils` line to resolve the conflict. Let me know if I should go the other way and and also cherry-pick the multireader move commit.
=> [17.06] Fix log readers can block writes indefinitely

components/cli/contrib/completion/bash/docker
backport completion script fixes:
1. docker/cli/pull/239 Add bash completion for `docker network create --ingress`
2. docker/cli/pull/246 Add bash completion for `label` filter of `prune` commands
3. docker/cli/pull/247 Add bash completion for `service create|update --entrypoint`
4. docker/cli/pull/248 Add bash completion for `network create --scope|--config-only|config-from`
5. docker/cli/pull/249 Fix bash completion for `network create --internal`
6. docker/cli/pull/250 Add bash completion for `service create --detach`
7. docker/cli/pull/251 Add bash completion for plugin events
8. docker/cli/pull/256 Add bash completion for `service create|update (update|rollback)-order`
9. docker/cli/pull/257 Add bash completion for `service create|update --network-(add|rm)`
10. docker/cli/pull/268 …
=> [17.06] backport various completion script updates

components/cli/vendor/github.com/docker/docker/client/container_wait.go
Backport fix:
* moby/moby/issues/33948 Docker wait hangs indefinitely for non-existent container
Into `components/cli/vendor/github.com/docker/docker` with cherry-pick moby/moby@4d2d2ea:
```
$ git cherry-pick -s -x -Xsubtree=components/cli/vendor/github.com/docker/docker 4d2d2ea
```
This fix was already included in 1dc2936 to `components/engine`, but is also needed in `components/cli/vendor`.
=> [17.06] Docker wait hangs indefinitely for non-existent container (vendor)

components/engine/Dockerfile
Backport:
* moby/moby#33748 Remove OSX cross stuff from main Dockerfile
With cherry-pick moby/moby@57f0e0c:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 57f0e0c
```
No conflicts.
=> [17.06] Remove OSX cross stuff from main Dockerfile

components/cli/vendor/github.com/docker/docker/volume/volume.go, components/engine/volume/volume.go
Backport fix:
* moby/moby/pull/33831 Do not error on relabel when relabel not supported
With cherry-pick moby/moby@ebfdfc5:
```
$ git cherry-pick -s -x -Xsubtree=components/engine ebfdfc5
$ git cherry-pick -s -x -Xsubtree=components/cli/vendor/github.com/docker/docker ebfdfc5
```
No conflicts.
=> [17.06] Do not error on relabel when relabel not supported

components/cli/cli/command/system/prune.go
Backport from upstream PRs:
* docker/cli/pull/118 Don't prune volumes on `docker system prune`
* docker/cli/pull/255 system prune: only warn for volumes if --volumes is given
With cherry-pick docker/cli@37fd612 and docker/cli@849b0e9:
```
$ git cherry-pick -s -x -Xsubtree=components/cli 37fd612 849b0e9
```
Conflict with `components/cli/cli/command/system/prune.go` but was able to resolve by taking the cherry-pick's change set.
=> [17.06] backport (cli) Don't prune volumes on docker system prune

components/cli/vendor/github.com/docker/docker/client/service_create.go, components/cli/vendor/github.com/docker/docker/client/service_update.go, components/engine/client/service_create.go, components/engine/client/service_update.go
Backport fix:
* moby/moby/pull/33867 Do not add duplicate platform information to service spec
With cherry-pick of moby/moby@da85b62:
```
$ git cherry-pick -s -x -Xsubtree=components/engine da85b62
$ git cherry-pick -s -x -Xsubtree=components/cli/vendor/github.com/docker/docker da85b62
```
=> [17.06] backport "Do not add duplicate platform information to service spec"

components/engine/builder/dockerfile/copy.go, components/engine/builder/dockerfile/dispatchers.go, components/engine/integration-cli/docker_api_build_test.go
cherry-pick fix:
* moby/moby/pull/33851 build: fix add from remote url
workaround for 17.06 to avoid bigger refactor because of merge conflicts
@dnephin @andrewhsu
=> [17.06] build: fix add from remote url

components/engine/api/server/middleware/debug.go, components/engine/api/server/middleware/debug_test.go
Backport fix:
* moby/moby/pull/33884 middleware: Redact secret data on "secret create"
With cherry-pick moby/moby@3fbc352:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 3fbc352
```
No conflicts.
=> [17.06] middleware: Redact secret data on "secret create"

components/engine/daemon/logger/journald/journald.go, components/engine/daemon/logger/syslog/syslog.go
Backport fix:
* moby/moby/pull/33832 Fix stderr logging for journald and syslog
With cherry-pick moby/moby@917050c:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 917050c
```
No conflicts.
=> [17.06] Fix stderr logging for journald and syslog

components/engine/pkg/gitutils/gitutils.go, components/engine/pkg/gitutils/gitutils_test.go
Backport fix from:
* moby/moby/pull/33696 Fix handling of remote "git@" notation
By cherry-pick of just the first commit, moby/moby@913eb99:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 913eb99
```
=> [17.06] Fix handling of remote "git@" notation

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/ca/external.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/clusters.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/configs.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/extensions.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/networks.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/nodes.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/object.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/resources.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/secrets.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/services.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/store/tasks.go
Bring in fixes on docker/swarmkit `bump_v17.06.1` branch at git commit docker/swarmkit@fbccf06:
- https://github.com/docker/swarmkit/pull/2281 - fixes an issue where some cluster updates
could be missed if a manager receives a catch-up snapshot from another manager
- https://github.com/docker/swarmkit/pull/2300 - fixes a possible memory issue if an
external CA sends an overlarge response
Note, this PR is a cherry-pick from https://github.com/docker/swarmkit/tree/bump_v17.06.1, which has one extra commit that enables that branch to pass CI (because `vndr` version changed) but which is not needed for this repo.
cc @aaronlehmann @andrewhsu @thaJeztah
=> [17.06] backport (swarmkit) cluster update and memory issue fixes

components/cli/cli/command/swarm/ca.go
Backport fix (each PR has just one git commit):
* docker/cli/pull/207 If `docker swarm ca` is not called with the `--rotate` flag, warn if other flags are passed
* docker/cli/pull/328 Fix warning in docker CLI when `swarm ca` is called with flags other than `--rotate`
With cherry-pick of docker/cli@32b43bc and docker/cli@4615c92:
```
$ git cherry-pick -s -x -Xsubtree=components/cli 32b43bc 4615c92
```
Conflict with `components/cli/cli/command/swarm/ca_test.go` in that the docker/cli@4615c92 cherry-pick wanted to modify it and it did not exist on the `17.06` branch. Resolved the conflict by not apply the diff to that file.
=> [17.06] backport (cli) If `docker swarm ca` is not called with the `--rotate` flag, warn if other flags are passed

components/engine/daemon/health.go
Backport fix:
* moby/moby#33781 Prevent a goroutine leak when healthcheck gets stopped
With cherry-pick moby/moby@67297ba:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 67297ba
```
No conflicts.
=> [17.06] Prevent a goroutine leak when healthcheck gets stopped

components/cli/docs/extend/plugins_authorization.md, components/cli/docs/reference/builder.md, components/cli/docs/reference/commandline/attach.md, components/cli/docs/reference/commandline/build.md, components/cli/docs/reference/commandline/cli.md, components/cli/docs/reference/commandline/dockerd.md, components/cli/docs/reference/commandline/exec.md, components/cli/docs/reference/commandline/ps.md, components/cli/docs/reference/commandline/service_create.md, components/cli/docs/reference/commandline/stack_deploy.md, components/cli/docs/reference/run.md, components/cli/experimental/docker-stacks-and-bundles.md, components/engine/api/swagger.yaml, components/engine/docs/api/version-history.md
backport various doc fixes, each PR has only 1 commit:
1. docker/cli/pull/164 Clarify ability to attach multiple time
2. docker/cli/pull/191 docs/reference/builder.md: mention that USER directive also allows to specify a user group
3. docker/cli/pull/198 Added usage example for -e for exec
4. docker/cli/pull/216 Fix Markdown formatting of experimental "stacks"
5. docker/cli/pull/222 Explain `stack deploy` with multiple Compose files
6. docker/cli/pull/225 Reformat filtering options in ps ref
7. docker/cli/pull/226 Fix small typo
8. docker/cli/pull/230 Remove specific config info about userns-remap
9. docker/cli/pull/241 Fix false Liquid errors
10. docker/cli/pull/244 Some builder docs improvements
11. docker/cli/pull/289 Provide examples for multiple uses of the same flag
12. …
=> [17.06] backport various docs fixes

components/cli/vendor/github.com/docker/docker/client/ping.go, components/cli/vendor/github.com/docker/docker/client/request.go, components/engine/client/ping.go, components/engine/client/ping_test.go, components/engine/client/request.go
Backport fix:
* moby/moby/pull/33827 Set ping version even on error
With cherry-pick moby/moby@27ef09a:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 27ef09a
```
No conflicts.
And copy of cherry-picked files to `vendor` of cli component:
```
$ cp components/engine/client/ping.go \
components/cli/vendor/github.com/docker/docker/client/ping.go
$ cp components/engine/client/request.go \
components/cli/vendor/github.com/docker/docker/client/request.go
```
=> [17.06] Set ping version even on error

components/engine/image/tarexport/load.go
Backport fix:
* moby/moby/pull/33647 Stop trying to load images on an incompatible OS
With cherry-pick of moby/moby@b9255e4:
```
$ git cherry-pick -s -x -Xsubtree=components/engine b9255e4
```
No need to cherry-pick into `componetns/cli/vendor` because file is not used by the client.
=> [17.06] backport fix "Stop trying to load images on an incompatible OS"

components/packaging/static/Makefile
Bring in PR docker/docker-ce-packaging/pull/34 check if build dir exists before chown.
Without this PR, `clean` target would fail if `build` dir not found within `components/packaging/static` dir.
=> check if build dir exists before chown

components/engine/hack/make/test-integration-cli
Picked from moby/moby#34206
```shell
git cherry-pick -x -s -Xsubtree="components/engine" 3cdd471
```
Integration test were failing in trial runs for docker-ce 17.07 due to
the lack of go-autogen being sourced in `hack/make.sh`. This re-adds
go-autogen to be sourced for test-integration-cli so that we can
actually run tests without the error found in:
https://github.com/moby/moby/pull/33857
(cherry picked from commit 3cdd471cac8193c34d8483255065c6c28a7b1645)
CC @andrewhsu @thaJeztah @dnephin
=> [17.07.x] Add go-autogen to integration tests

components/engine/libcontainerd/remote_unix.go, components/engine/vendor.conf, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/README.md, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/process_state_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/spec_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/state_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/template.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/unmarshal.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/upgrade.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/vendor.conf, components/engine/vendor/github.com/crosbymichael/upgrade/vendor.conf
To address issue:
* docker/for-linux/issues/49 Containers can not start after docker upgrade from 17.03.0-ce to 17.06.0-ce
=> [engine] Graceful upgrade of containerd and runc state files upon live-restore

components/engine/pkg/mount/mounter_linux.go, components/engine/pkg/mount/mounter_linux_test.go
This is a backport of https://github.com/moby/moby/pull/34077. Cherry-pick moby/moby@3a1ab5b:
```
git cherry-pick -s -x -Xsubtree=components/engine 3a1ab5b
```
There was a conflict where it seems like the `syscall` had changed in engine master, but I just used the `syscall` import here.
cc @justincormack @tych0 @andrewhsu
=> [17.06.1] Backport engine userns secrets-mounting fix

components/packaging/deb/common/rules
```shell
git cherry-pick -x -s -Xsubtree="components/packaging" 3a548f8
```
Cherry-picked from docker/docker-ce-packaging#37
Tried out make -C in this scenario and it did not seem to function
correctly, changed to cd.
(cherry picked from commit 3a548f8815d5308b197abea1e39f0a0a4939c4f2)
CC @andrewhsu
=> [17.07.x] Change make -C to a cd command

components/engine/daemon/build.go, components/engine/integration-cli/docker_api_build_test.go
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
(cherry picked from commit e430b58811813084df2b9f8b1a9e929114b2187a)
=> builder: fix copy —from conflict with force pull

components/engine/libcontainerd/remote_unix.go, components/engine/vendor.conf, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/README.md, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/process_state_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/spec_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/state_gen.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/template.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/unmarshal.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/upgrade.go, components/engine/vendor/github.com/crosbymichael/upgrade/v17_06_1/vendor.conf, components/engine/vendor/github.com/crosbymichael/upgrade/vendor.conf
Bring in fix:
* https://github.com/docker/docker-ce/pull/117 Graceful upgrade of containerd and runc state files upon live-restore
With cherry-pick 358c36e:
```
$ git cherry-pick -xs 358c36e93093961a512face64b6b7701b04e55a2
```
No conflicts.
=> [17.07] Graceful upgrade of containerd and runc state files upon live-restore

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/logbroker/broker.go, components/engine/vendor/github.com/docker/swarmkit/manager/manager.go, components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/global/global.go, components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/restart/restart.go, components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go, components/engine/vendor/github.com/docker/swarmkit/manager/watchapi/server.go, components/engine/vendor/github.com/docker/swarmkit/manager/watchapi/watch.go
This vendoring comes from the [swarmkit `bump_17.07`](https://github.com/docker/swarmkit/commits/bump_v17.07) branch, and includes the following fixes:
- https://github.com/docker/swarmkit/pull/2288 (Allow updates of failed services with restart policy "none")
- https://github.com/docker/swarmkit/pull/2304 (Reset restart history when task spec changes)
- https://github.com/docker/swarmkit/pull/2309 (updating the service spec version when rolling back)
- https://github.com/docker/swarmkit/pull/2310 (fix for slow swarm shutdown)
cc @aaronlehmann
=> [17.07] Re-vendor swarmkit 

components/engine/api/swagger.yaml, components/engine/api/types/volume.go, components/engine/docs/api/version-history.md
Cherry-picks of:
ping @aaronlehmann @andrewhsu @tiborvass PTAL
=> [17.06.1] Swagger and API docs cherry-picks

components/engine/Dockerfile, components/engine/Dockerfile.aarch64, components/engine/Dockerfile.armhf, components/engine/Dockerfile.ppc64le, components/engine/Dockerfile.s390x, components/engine/Dockerfile.simple, components/engine/pkg/archive/archive_test.go, components/engine/vendor.conf, components/engine/vendor/archive/tar/common.go, components/engine/vendor/archive/tar/format.go, components/engine/vendor/archive/tar/reader.go, components/engine/vendor/archive/tar/stat_atim.go, components/engine/vendor/archive/tar/stat_atimespec.go, components/engine/vendor/archive/tar/stat_unix.go, components/engine/vendor/archive/tar/strconv.go, components/engine/vendor/archive/tar/writer.go
Backport fix:
* moby/moby/pull/34106 Fix tar prefix header
With cherry-pick moby/moby@72df48d and moby/moby@4a3cfda:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 72df48d 4a3cfda
```
No conflicts.
=> [17.06] backport Fix tar prefix header

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/logbroker/broker.go, components/engine/vendor/github.com/docker/swarmkit/manager/manager.go, components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go, components/engine/vendor/github.com/docker/swarmkit/manager/watchapi/server.go, components/engine/vendor/github.com/docker/swarmkit/manager/watchapi/watch.go
Vendor to docker/swarmkit@a0a7f6f.
This includes swarmkit fixes for the following 3 issues:
- https://github.com/docker/swarmkit/pull/2309 (updating the service spec version when rolling back)
- https://github.com/docker/swarmkit/pull/2310 (fix for slow swarm shutdown)
- https://github.com/docker/swarmkit/pull/2323 (run watchapi server on all managers)
Comparing differences: https://github.com/docker/swarmkit/compare/fb828ce...a0a7f6f
=> [17.06] Re-vendor swarmkit for various fixes

components/engine/daemon/cluster/tasks.go
Backport of moby/moby#34235
GetTasks can call GetService and GetNode with the read lock held. These
methods try to aquire the read side of the same lock. According to the
sync package documentation, this is not safe:
> If a goroutine holds a RWMutex for reading, it must not expect this or
> any other goroutine to be able to also take the read lock until the
> first read lock is released. In particular, this prohibits recursive
> read locking. This is to ensure that the lock eventually becomes
> available; a blocked Lock call excludes new readers from acquiring the
> lock.
Fix GetTasks to use the lower-level getService and getNode methods
instead. Also, use lockedManagerAction to simplify GetTasks.
=> [17.06] cluster: Avoid recursive RLock

components/engine/daemon/delete.go, components/engine/daemon/graphdriver/aufs/aufs.go
Backport moby/moby#33960 Fix error handling with not-exist errors on remove
Cherry-pick commit moby/moby@d42dbdd
```
$ git cherry-pick -s -x -Xsubtree=components/engine d42dbdd
```
=> [17.06] Fix error handling with not-exist errors on remove

components/cli/contrib/completion/bash/docker, components/cli/docs/reference/builder.md, components/cli/docs/reference/commandline/cp.md, components/cli/docs/reference/commandline/events.md, components/cli/docs/reference/commandline/search.md, components/cli/docs/reference/commandline/service_create.md, components/cli/docs/reference/commandline/service_update.md, components/cli/docs/reference/commandline/volume_ls.md
cherry-picks of;
- https://github.com/docker/cli/pull/223 https://github.com/docker/cli/commit/e4c70d390de72bfa9bbb6d016a47a08141295bf3 ("Update the cp command docs to include archive")
- https://github.com/docker/cli/pull/308 https://github.com/docker/cli/commit/4f3a8aecad56cf27191004b40aa2cd6a42fc9ce6 ("Fix typo (proceed -> precede)")
- https://github.com/docker/cli/pull/314 https://github.com/docker/cli/commit/8639c9baf8252ccdcfb3360e0d5568c01a3942ce ("docs: add filter scope for command events and more cluster events")
- https://github.com/docker/cli/pull/331 https://github.com/docker/cli/commit/bd64ad25fb73aeff9a51ad7168904253569447c0 ("Fix filters displaying for docker search")
- https://github.com/docker/cli/pull/333 https://github.com/docker/cli/commit/2880030814986e71010b573899b1f9 …
=> [17.06] CLI reference docs cherry-picks (and 1 completion fix)

components/engine/container/state.go
Backport fixes:
* moby/moby/pull/33843 Set unpaused state when receiving 'stateExit' event
* moby/moby/pull/34071 Keep pause state when restoring container's status
With cherry pick git commit moby/moby@fe1b4cf and moby/moby@977c404:
```
$ git cherry-pick -s -x -Xsubtree=components/engine fe1b4cf
$ git cherry-pick -s -x -Xsubtree=components/engine 977c404
```
No conflicts on both.
=> [17.06] Set unpaused state when receiving 'stateExit' event

components/engine/daemon/logger/awslogs/cloudwatchlogs.go, components/engine/daemon/logger/awslogs/cloudwatchlogs_test.go
cherry-picked from https://github.com/moby/moby/pull/34296/commits/0fd5a0bab79f20f910cb7551ec34158a32e05f5a (https://github.com/moby/moby/pull/34296)
(no conflicts, patch applied cleanly)
ping @andrewhsu @samuelkarp PTAL
=> [17.06.1] Fix awslogs driver repeating last event - #34292

components/engine/api/server/router/network/network_routes.go
Starting 17.06 swarm service create supports service creates with predefined
networks like host and bridge. Due to the nature of the feature, swarm manager
has a swarm scope predefined networks in addition to local scoped
predefined networks on all nodes. However network inspects for swarm scoped
predefined networks was not possible. The fix adds support for network inspect
for swarm scoped predefined networks.
Signed-off-by: Abhinandan Prativadi <abhi@docker.com>
Since the cherry pick of moby/moby#34302 is not possible due to function difference. Raising this PR in docker-ce
=> [17.06] Changing get network request to return predefined network in swarm

components/engine/api/swagger.yaml
cherry-pick of https://github.com/moby/moby/commit/fc48b5529dca3907ade273921a14906be796e333 (https://github.com/moby/moby/pull/34247)
no conflicts
=> [17.06.1] Fix RestartPolicy default value

components/cli/cli/command/system/prune.go
cherry picked from commit https://github.com/docker/cli/commit/3c095dc546e9c90afcfb1ca1695b408d813b4306 (https://github.com/docker/cli/pull/311)
conflicted with https://github.com/docker/docker-ce/commit/f7a9f9fb67187e89564037c8dbd25eeb6580b242 (https://github.com/docker/docker-ce/pull/109)
The "until" filter is supported by all object types, except for
volumes.
Before this patch, the "until" filter would attempted to be used for the volume
prune endpoint, resulting in an error being returned by the daemon, and
further prune endpoints (networks, images) to be skipped.
$ docker system prune --filter until=24h --filter label=label.foo=bar
WARNING! This will remove:
- all stopped containers
- all volumes not used by at least one container
- all networks not used by at least one container
- …
=> [17.06] Error if "until" filter is combined with "--volumes" on system prune

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/common/caller.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/joinleave.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_serf.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/overlay.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go, components/engine/vendor/github.com/docker/libnetwork/iptables/iptables.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/broadcast.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/cluster.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/delegate.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/event_delegate.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdb.go, components/engine/vendor/github.com/docker/libnetwork/service_linux.go
Re-vndr libnetwork to latest git commit docker/libnetwork@f0b9939 of [bump_17.06.0 branch](https://github.com/docker/libnetwork/tree/bump_17.06.0) which brings in the following changes:
* docker/libnetwork/pull/1869 [17.06 backport] Funnel peerAdd and peerDelete in a channel
* docker/libnetwork/pull/1871 [backport 17.06] iptables: jump to DOCKER-USER first
* docker/libnetwork/pull/1873 [17.06 backport] Avoid flakiness of TestLinkContainers
* ~docker/libnetwork/pull/1875 [backport 17.06] Fixes bug that mistook gw6 for gw.~
* docker/libnetwork/pull/1878 [17.06] backport networkdb fixes
EDIT: the PR docker/libnetwork/pull/1875 was reverted with docker/libnetwork@f0b9939
```
$ vi vendor.conf # bump to git commit f0b9939
$ vndr …
```
=> re-vndr libnetwork to latest on bump_17.06.0 branch

components/packaging/static/Makefile
Don't really know how this commit didn't fully get in but this basically removes the $(HASH_CMD) from the basic static targets.
Without this the `cross-win` target for `components/packaging/static/Makefile` will fail.
Cherry-picked from: https://github.com/docker/docker-ce-packaging/pull/1
```
git cherry-pick -x -s -Xsubtree="components/packaging" 533a843393bd7c3674074ec9af73c8e666fc7484
```
(cherry picked from commit 533a843393bd7c3674074ec9af73c8e666fc7484)
=> [17.06] Move the hashing of files to its own target

components/engine/daemon/container_operations.go
Backport fix:
* moby/moby/pull/33456 Lock container while connecting to a new network.
To address issue:
`ConnectToNetwork` is modfying the container but is not locking theobject.
This was backported to 17.03 but did not make it to 17.06.
=> [17.06] backport fix for lock container while connecting to a new network

components/cli/cli/command/stack/deploy_composefile.go, components/cli/cli/command/stack/deploy_composefile_test.go
To backport fix:
- docker/cli#362 Skip inspect of built-in networks on stack deploy
Cherry pick conflict was resolved by retaining the signature of the `NetworkInspect` operation as `func(context.Context, string, bool) (types.NetworkResource, error)`
This PR was behaviorally validated via `make static` and using the resulting binaries to deploy a compose file with an external network named `host`.
cc @dnephin @vdemeester @thaJeztah 
Operations followed:
```
$ git clone git@github.com:docker/docker-ce # fresh clone
$ cd docker-ce # enter the working dir
$ git checkout 17.06 # checkout the branch
$ git fetch git@github.com:docker/cli master:cli # get the git commits from upstream cli
$ git cherry-pick -s -x -Xsubtree=components/cli 7f53c99 # pick just the one commit
```
Supercedes …
=> [17.06] backport Skip inspect of built-in networks on stack deploy

components/engine/container/container.go
backport:
* moby/moby/pull/34194 Fixing issue with driver opt not passed to drivers.
with cherry pick moby/moby@bcb55c6
```
$ git cherry-pick -s -x -Xsubtree=components/engine bcb55c6
```
=> [17.07] backport Fixing issue with driver opt not passed to drivers

components/engine/container/view.go, components/engine/container/view_test.go
backport:
* moby/moby#34274 Fix Delete on nonexistent container.
with cherry pick moby/moby@1d9546f
```
$ git cherry-pick -s -x -Xsubtree=components/engine  1d9546f
```
=> [17.07] backport Fix delete container

components/engine/daemon/build.go
releaseableLayer includes automatic handling for creating a read/write layer and mounting it on a call to Mount(), but then does not correspondingly unmount the layer before trying to delete it, which will fail for some graphdrivers. Commit on a releaseable layer also leaks the tarstream for the layer. To fix this, the stream close is deferred in Commit and releaseRWLayer now correctly handles unmounting the layer before trying to delete it.  In addition, the changes include better error handling in Release() to make sure that errors are returned to the caller for failures on read/write layers instead of being ignored.# Please enter the commit message for your changes. Lines starting
cherry picked from commit https://github.com/moby/moby/commit/1d457999c4540aacda68f834bdb3c6f220ce3fd5 - …
=> [17.07] Fixing releaseableLayer handling of layer streams and mounts.

components/engine/daemon/logger/awslogs/cloudwatchlogs.go, components/engine/daemon/logger/awslogs/cloudwatchlogs_test.go
cherry-picked from https://github.com/moby/moby/pull/34296/commits/0fd5a0bab79f20f910cb7551ec34158a32e05f5a (https://github.com/moby/moby/pull/34296)
(no conflicts, patch applied cleanly)
ping @andrewhsu @samuelkarp PTAL
=> [17.07] Fix awslogs driver repeating last event - #34292

components/engine/daemon/delete.go, components/engine/daemon/graphdriver/aufs/aufs.go
=> [17.07] Fix error handling with not-exist errors on remove

Makefile
port top-level make target `vendor` to 17.07 codeline from #148 
```
$ git cherry-pick -s -x 21205da
```
no conflicts
=> [17.07] Add make vendor target

components/cli/cli/command/cli.go
cherry-picked from https://github.com/docker/cli/commit/2831a04cbad65e11081b0cd189599767fce3646a (https://github.com/docker/cli/pull/415/) - no conflicts
Some network environments may have NATs, proxies, or gateways which
kill idle connections. There are many Docker API operations which may
be idle for long periods of time (such as ContainerWait and ContainerAttach)
and may result in unexpected connection closures or hangs if TCP keepalives
are not used.
This patch updates the default HTTP transport used by the Docker client
package to enable TCP Keep-Alive with a keep-alive interval of 30 seconds.
It also sets a connect timeout of 30 seconds.
ping @dhiltgen @dnephin @jlhawn @andrewhsu PTAL
=> [17.07] Enable TCP Keep-Alive in Docker client

components/engine/plugin/manager.go, components/engine/plugin/manager_linux.go, components/engine/plugin/manager_solaris.go, components/engine/plugin/manager_windows.go
backport:
* moby/moby/pull/34374 Make plugins dir private.
with cherry pick moby/moby@0c2821d
```
$ git cherry-pick -s -x -Xsubtree=components/engine 0c2821d
```
=> [17.07] backport Make plugins dir private

components/engine/api/server/router/network/network_routes.go, components/engine/integration-cli/docker_cli_network_unix_test.go
backport:
* moby/moby/pull/34395 Fix api server null pointer def on inspect/ls null ipam-driver networks.
with cherry pick moby/moby@beebfc0
```
$ git cherry-pick -s -x -Xsubtree=components/engine beebfc0
```
=> [17.07] backport Fix api server null pointer def on inspect/ls null ipam-driver networks

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/agent.go, components/engine/vendor/github.com/docker/libnetwork/common/caller.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/joinleave.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_serf.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/overlay.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go, components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdb.go
Update vendor of libnetwork to latest on bump_17.07 branch. Comparing changes: docker
https://github.com/docker/libnetwork/compare/449a722...9647f99
```
$ vndr github.com/docker/libnetwork
```
Brings in upstream fix:
* docker/libnetwork/pull/1896 [Backport 17.07] service connectivity issue
=> [17.07] vndr libnetwork to latest bump_17.07

components/engine/libcontainerd/remote_unix.go
cherry picked from commit https://github.com/moby/moby/pull/32590/commits/02ce73f62e73e78a4ec29b29fb2ba552221fe885 (https://github.com/moby/moby/pull/32590)
no conflicts
Description:
Kill docker-containerd continuously, and use kill -SIGUSR1 <dockerpid>
to check docker callstacks. And we will find that event
handler: startEventsMonitor or handleEventStream will exit.
This will only happen when system is busy, containerd need more time to
startup, and the monitor gorotine maybe exit.
=> [17.06] Fix when containerd restarted, event handler may exit

components/engine/plugin/manager.go, components/engine/plugin/manager_linux.go, components/engine/plugin/manager_solaris.go, components/engine/plugin/manager_windows.go
backport:
* moby/moby/pull/34374 Make plugins dir private.
with cherry pick moby/moby@0c2821d
```
$ git cherry-pick -s -x -Xsubtree=components/engine 0c2821d
```
=> [17.06] backport Make plugins dir private

components/engine/api/server/router/network/network_routes.go, components/engine/integration-cli/docker_cli_network_unix_test.go
cherry-picked from https://github.com/moby/moby/pull/34395/commits/beebfc0cf6240c8af511eb4d7e29314c8de6ddf2 (https://github.com/moby/moby/pull/34395)
applied cleanly, no merge conflicts
- When a network is created with the null ipam driver, docker api server
thread will deference a nil pointer on `docker network ls` and on
`docker network inspect <nw>`. This because buildIpamResource()
assumes a gateway address is always present, which is not correct.
=> [17.06] Fix api server null pointer def on inspect/ls null ipam-driver networks

components/engine/api/swagger.yaml, components/engine/daemon/cluster/executor/container/executor.go, components/engine/daemon/cluster/services.go, components/engine/integration-cli/docker_api_swarm_service_test.go
backport:
* moby/moby/pull/34455 Hide swarm plugins behind experimental flag.
with cherry pick moby/moby@4930020
```
$ git cherry-pick -s -x -Xsubtree=components/engine 4930020
```
=> [17.07] backport for Hide swarm plugins behind experimental flag

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go
bring in fix to docker-ce 17.07 branch:
* docker/libnetwork/pull/1905 [backport 17.07] PeerDbDelete was passing the wrong field
by vndr libnetwork to tip of https://github.com/docker/libnetwork/tree/bump_17.07
comparison of changes: https://github.com/docker/libnetwork/compare/9647f99...230db20
this is how we do it:
```
$ vndr github.com/docker/libnetwork
```
=> [17.07] vndr libnetwork to bump_17.07 to fix peerDeleteOp

components/cli/vendor/github.com/docker/docker/client/client.go, components/cli/vendor/github.com/docker/docker/client/ping.go, components/engine/client/client.go, components/engine/client/ping.go
backport fix:
* moby/moby/pull/34487 Fix requests for docker host ending with slash
with cherry pick of git commit https://github.com/moby/moby/pull/34487/commits/823e88d931 (no conflicts):
```
$ git cherry-pick -s -x -Xsubtree=components/engine 823e88d
```
and update of `components/cli/vendor/github.com/docker/docker` with the changes to `components/engine`
=> [17.07] backport Fix requests for docker host ending with slash

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go
vndr libnetwork to bring in fix:
* docker/libnetwork/pull/1913 [backport 17.07] Overlay fix for IP reuse
comparison of changes from the libnetwork repo: https://github.com/docker/libnetwork/compare/230db20...4a242db
=> [17.07] vndr libnetwork to bring in lock fix

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go
vndr libnetwork to specifically bring in this fix:
* docker/libnetwork#1912 [backport 17.06] Overlay fix for IP reuse
comparison of changes from the libnetwork repo: https://github.com/docker/libnetwork/compare/2102668...9397626
=> [17.06] vndr libnetwork to bring in fix for overlay network ip reuse

components/cli/cli/command/cli.go
cherry-picked from https://github.com/docker/cli/commit/2831a04cbad65e11081b0cd189599767fce3646a (https://github.com/docker/cli/pull/415/) - no conflicts
Some network environments may have NATs, proxies, or gateways which
kill idle connections. There are many Docker API operations which may
be idle for long periods of time (such as ContainerWait and ContainerAttach)
and may result in unexpected connection closures or hangs if TCP keepalives
are not used.
This patch updates the default HTTP transport used by the Docker client
package to enable TCP Keep-Alive with a keep-alive interval of 30 seconds.
It also sets a connect timeout of 30 seconds.
ping @dhiltgen @dnephin @jlhawn PTAL
=> [17.06] backport "Enable TCP Keep-Alive in Docker client"

components/engine/daemon/graphdriver/aufs/aufs.go, components/engine/daemon/graphdriver/aufs/aufs_test.go
backport fix:
* moby/moby#34587 Fix error removing diff path
with cherry-pick of https://github.com/moby/moby/pull/34587/commits/276b44608b04f08bdf46ce7c816b1f744bf24b7d
```
$ git cherry-pick -s -x -Xsubtree=components/engine 276b446
```
conflict with `aufs.go` file resolved by making sure stuff like `unix.EBUSY` was `syscall.EBUSY` because the docker-ce 17.06 branch has not backported https://github.com/moby/moby/commit/069fdc8
=> [17.06] backport fix for removing diff path

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go
re-vndr swarmkit to latest on [bump_v17.06](https://github.com/docker/swarmkit/tree/bump_v17.06) branch to pull in fix:
* https://github.com/docker/swarmkit/pull/2351 IsTaskDirty: Ignore PullOptions for running tasks
comparison of changes: https://github.com/docker/swarmkit/compare/a0a7f6f...bf3d9a2
```
$ vndr github.com/docker/swarmkit
```
=> [17.06] vndr swarmkit to bring in fix for PullOptions

CHANGELOG.md
These issues also exist in the release notes. They should be fixed there as well.
=> [17.07] Fix wrong changelog entries

components/engine/integration-cli/docker_cli_rmi_test.go, components/engine/integration-cli/docker_cli_run_unix_test.go
Attempts to remedy these failing tests:
```
DockerSuite.TestRmiContainerImageNotFound
DockerSuite.TestRmiImageIDForceWithRunningContainersAndMultipleTags
```
=> [17.09] Changes error check form NotNil to IsNil

components/engine/integration-cli/docker_cli_run_test.go
```
❯ git cherry-pick -x -s -Xsubtree="components/engine" fff605c3b3557acf6bf793813d695fba59d7fa21
[fix_test_run_environment dff328c8a6] Fix a bad assumption
Author: Daniel Nephin <dnephin@docker.com>
Date: Wed Sep 6 17:32:56 2017 -0400
1 file changed, 1 insertion(+), 1 deletion(-)
```
**NOTE**: Was clean
If the empty variable happens to be sorted to the end of the list then TrimSpace()
would remove it. Instead only strip the single trailing newline.
Signed-off-by: Daniel Nephin <dnephin@docker.com>
(cherry picked from commit fff605c3b3557acf6bf793813d695fba59d7fa21)
ping @dnephin @vieux @andrewhsu
=> [17.09] Fix test run environment

components/engine/Dockerfile.aarch64, components/engine/Dockerfile.armhf, components/engine/Dockerfile.ppc64le, components/engine/Dockerfile.s390x, components/engine/daemon/graphdriver/overlay/copy.go, components/engine/pkg/archive/archive_unix.go
```
git cherry-pick -x -s -Xsubtree="components/engine" 7c9e64a2e1891bf1020d9312a18741c734fa1cd6 0c0047e67f8ee73f73465ac60ccebbd16260ab46 0120303d8ea4a1d9f8920ac4dba80521072e8536
```
*NOTE*: Cherry pick was clean
Addresses issues where armhf packages were not being built correctly due to `gometalinter` failures.
Relates to: https://github.com/moby/moby/pull/34625#issuecomment-326772200
=> [17.09] Fix metalinter conversion errors

components/engine/Dockerfile, components/engine/Dockerfile.aarch64, components/engine/Dockerfile.armhf, components/engine/Dockerfile.ppc64le, components/engine/Dockerfile.s390x
To address:
* https://github.com/moby/moby/pull/34844 Fix fetching LVM2 sources
cherry-picked git commit moby/moby@a436d8a
```
$ git cherry-pick -s -x -Xsubtree=components/engine a436d8a
```
no conflicts with the cherry-pick
=> [17.09] backport fix to get static builds going

Makefile
Recently submitted a PR to the moby-components script to account for older versions of git trying to update components. https://github.com/shykes/moby-extras/pull/2
=> Hash needs to be updated for moby-components script

components/cli/docs/yaml/yaml.go
Backport of https://github.com/docker/cli/pull/523 for 17.09
**- What I did**
While looking at https://github.com/docker/docker.github.io/issues/3886, I noticed there's some information not included in the generated YAML for the documentation that could be useful. This PR contains two patches that adds additional information about commands and flags;
The first patch adds aditional information about command flags to the YAML files that are generated for the reference documentation.
The following fields are added for each flag:
Property          | Type      | Description
------------------|-----------|---------------------------------------------------------------------------------------
value_type        | String    | The "type" of value to be passed to this flag (e.g., `uint64`, `list`) …
=> [17.09] Add more information to the generated YAML for documentation

components/cli/docs/deprecated.md, components/engine/api/server/server.go, components/engine/cmd/dockerd/config_unix.go, components/engine/cmd/dockerd/daemon.go, components/engine/daemon/config/config.go
The `--enable-api-cors` flag was deprecated in https://github.com/moby/moby/commit/f3dd2db,
and marked for removal in docker 17.09 through https://github.com/moby/moby/commit/85f92ef.
This patch removes the deprecated flag.
cherry-pick of:
https://github.com/moby/moby/pull/34821
https://github.com/docker/cli/pull/524
=> [17.09] Backport remove cors headers flag

components/cli/cli/compose/convert/service.go
Backport of https://github.com/docker/cli/pull/509 for 17.09
From the original upstream PR:
> `docker stack deploy` keeps restarting services it doesn't need to (no changes)
> because the entries' order gets randomized at some previous (de)serialization.
> Maybe it would be worth looking into this at a higher level and ensure
> all (de)serialization happens in an ordered collection.
>
> This quick fix sorts secrets and configs (in place, mutably) which ensures the
> same order for each run.
>
> Based on
> https://github.com/moby/moby/pull/30506
>
> Fixes
> https://github.com/moby/moby/issues/34746
(cherry picked from commit https://github.com/docker/cli/commit/27e8bdf32bbcc49ff3f8201b6da26aba567aa58e)
=> [17.09] sort secrets and configs to ensure idempotence

components/engine/daemon/volumes.go, components/engine/integration-cli/docker_api_containers_test.go, components/engine/volume/local/local.go
cherry-pick of:
- https://github.com/moby/moby/pull/34684 ("Set selinux label on local volumes from mounts API")
- https://github.com/moby/moby/pull/34761  ("Some cleanup of mount create API test")
the last one was needed to get a clean cherry-pick
ping @cpuguy83 PTAL
=> [17.09] Set selinux label on local volumes from mounts API

components/engine/daemon/logger/splunk/splunk.go, components/engine/daemon/logger/splunk/splunk_test.go
back port of https://github.com/moby/moby/pull/34520 for 17.09
Splunk HEC does not accept log events with an empty string or a
whitespace-only string.
(cherry picked from commit 5f6d6a5093a4db799f9c1a6bb82eed1eea13ec0c)
=> [17.09] Fixed `raw` mode splunk logger

components/engine/daemon/graphdriver/overlay2/mount.go
back port of https://github.com/moby/moby/pull/34863
(cherry picked from commit 9f38923901352459bb621d0b3587a6517e67eeb3)
=> [17.09] back port Close pipe if mountFrom failed.

components/engine/daemon/daemon_unix.go
back port of https://github.com/moby/moby/pull/34863
This is kernel config available in RHEL7.4 based kernels that enables
mountpoint removal where the mountpoint exists in other namespaces.
In particular this is important for making this pattern work:
```
umount -l /some/path
rm -r /some/path
```
Where `/some/path` exists in another mount namespace.
Setting this value will prevent `device or resource busy` errors when
attempting to the removal of `/some/path` in the example.
This setting is the default, and non-configurable, on upstream kernels
since 3.15.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit 83c2152de503012195bd26069fd8fbd2dea4b32f)
=> [17.09] back port Automatically set `may_detach_mounts=1` on startup

components/engine/daemon/container_operations_unix.go
back port of https://github.com/moby/moby/pull/34732
Without relabel these files, SELinux-enabled containers will show
"permission denied" errors for configuration files mounted with
`docker server create ... --config ... ...`.
(cherry picked from commit 472c03a8c364090afb88258b3dd9748183c29d05)
=> [17.09] Relabel config files.

components/engine/vendor.conf, components/engine/vendor/github.com/Microsoft/hcsshim/container.go, components/engine/vendor/github.com/Microsoft/hcsshim/interface.go
To bring in fixes for windows
Effectively backporting these changes upstream:
* https://github.com/moby/moby/pull/34771 Revendor Microsoft/hcsshim @ v0.6.4
* https://github.com/moby/moby/pull/34775 Update hcsshim to v0.6.5
Comparison of changes in upstream: https://github.com/Microsoft/hcsshim/compare/v0.6.3...v0.6.5
This is how i did it:
```
$ vndr github.com/Microsoft/hcsshim
```
=> [17.09] vndr Microsoft/hcsshim to v0.6.5

Makefile
comparison of upstream differences: https://github.com/shykes/moby-extras/compare/f79265f...ab7c118
=> update moby-extras tool fixes git param

components/cli/cli/command/container/run.go
To remedy hanging tests as addressed in https://github.com/docker/cli/pull/577
Signed-off-by: Stephen J Day <stephen.day@docker.com>
(cherry picked from commit e78772af4dca453ed97ff25b03adbaec2054859a)
=> [17.10] ensure channel is allocated

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_cp_from_container_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/docker_cli_rmi_test.go, components/engine/integration-cli/docker_cli_service_scale_test.go, components/engine/integration-cli/docker_cli_stats_test.go, components/engine/integration-cli/docker_cli_swarm_test.go, components/engine/integration-cli/docker_cli_update_unix_test.go
This remedies tests that are known to fail when comparing the `master` version of both the `cli` and `engine` component.
Most (if not all) of the test failures are not related to functional code but instead related to test code.
* Changes error checking from `NotNil` to `IsNil` for `rmi -f` tests
* Skips over `DockerTrustSuite` tests that are known to fail with recent CLI changes, cc @riyazdf 
* Changes an `Lstat` to a regular `Stat`, cc @corbin-coleman 
* Shortens a container ID search to only include the first 12 characters, cc @corbin-coleman 
* Fixes a flaky test on s390x related to Kernel Version comparison, cc @tophj-ibm
=> [17.10] Fix tests for 17.10 release

components/packaging/deb/ubuntu-trusty/Dockerfile.armv7l
```
git cherry-pick -s -x -Xsubtree=components/packaging 8e177368d0a30614a7ba615f3c2f2ede1e21ff8e
```
Relates to https://github.com/docker/docker-ce-packaging/pull/54
Was getting 404's with the old one, consider this one temporary until
canonical fixes their stuff.
Related:
https://bugs.launchpad.net/cloud-images/+bug/1711735
(cherry picked from commit 8e177368d0a30614a7ba615f3c2f2ede1e21ff8e)
=> Switches ubuntu trusty mirror to one that works

components/engine/distribution/pull_v2.go, components/engine/distribution/pull_v2_unix.go, components/engine/distribution/pull_v2_windows.go
Backport fix:
- https://github.com/moby/moby/pull/35090
- https://github.com/moby/moby/pull/35117
with cherry pick of https://github.com/moby/moby/commit/38aef56e1fcb8ea318df98c89cf002267b88a136 and https://github.com/moby/moby/commit/8ed8f4a71d7e1a936fa077b4348b7375c81746a6:
```
git cherry-pick -s -x -Xsubtree=components/engine 38aef5
git cherry-pick -s -x -Xsubtree=components/engine 8ed8f4
```
Conflict with `pull_v2.go` in https://github.com/moby/moby/commit/8ed8f4a71d7e1a936fa077b4348b7375c81746a6 resolved by reverting back to detecting the OS the previous way (before it was supplied as a parameter) and also only sorting for Windows (like in current master) as 17.10 has not backported https://github.com/moby/moby/commit/d98ecf2d6cdad7dae65868398440cfdc855e5263.
=> [17.10] Backport version fix for Windows manifest lists

components/cli/contrib/completion/bash/docker, components/cli/docs/deprecated.md, components/cli/docs/reference/commandline/dockerd.md, components/cli/docs/reference/commandline/rmi.md, components/cli/docs/reference/commandline/service_create.md, components/cli/docs/reference/commandline/stack_deploy.md
All cherry-picks went in clean, no conflicts.
https://github.com/docker/cli/pull/610 Update bash completion and deprecation for synchronous service updates
```
$ git cherry-pick -s -x -Xsubtree=components/cli 60bfaba 20d9cec
[d f26232e8f6] Update bash completion for synchronous `docker service` commands
Author: Harald Albers <github@albersweb.de>
Date: Sat Oct 7 13:57:26 2017 +0200
1 file changed, 3 insertions(+), 3 deletions(-)
[d 6fc2c6b8c5] Update deprecation for synchronous service updates
Author: Harald Albers <github@albersweb.de>
Date: Sat Oct 7 14:28:56 2017 +0200
1 file changed, 5 insertions(+), 2 deletions(-)
```
https://github.com/docker/cli/pull/611 Add bash completion for `stack deploy --resolve-image`
```
$ git cherry-pick -s -x -Xsubtree=components/cli 9559b9b
[d …
```
=> [17.10] backport doc fixes and shell completion script fixes

components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/scheduler/filter.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/raft.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/transport/peer.go, components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/transport/transport.go
Backport fixes:
* https://github.com/docker/swarmkit/pull/2402 [17.10] Don't filter nodes if logdriver==none
* https://github.com/docker/swarmkit/pull/2403 [17.10] Increase gRPC request timeout to 20 seconds when sending snapshots
By update of swarmkit vendor to tip of `bump_v17.10` branch:
```
$ vndr github.com/docker/swarmkit
```
Comparison of changes in upstream swarmkit: https://github.com/docker/swarmkit/compare/872861d...1d2bc2e
=> [17.10] re-vndr swarmkit to 1d2bc2e

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/trust_server_test.go
- same notary mismatch from 17.10
- updated stderr output from docker/cli#636
cc @andrewhsu @seemethere
=> [17.11] update trust tests for 17.11

components/engine/integration-cli/docker_cli_cp_from_container_test.go, components/engine/integration-cli/docker_cli_rmi_test.go
Even though the PRs to the upstream moby/moby may pass, these tests fail consistently when integrated with the docker-ce repo which uses a newer version of docker/cli.
3 separate commits to disable the tests because they either need to be removed upstream or need adjustment.
Commit 38805b0 can be taken care of when docker/cli#654 is merged.
=> [17.11] skip tests for now that are known to need adjustment

components/packaging/deb/Makefile, components/packaging/deb/ubuntu-artful/Dockerfile.armv7l, components/packaging/deb/ubuntu-artful/Dockerfile.ppc64le, components/packaging/deb/ubuntu-artful/Dockerfile.s390x, components/packaging/deb/ubuntu-artful/Dockerfile.x86_64
Cherry picked from: https://github.com/docker/docker-ce-packaging/pull/55
```
git cherry-pick -s -x -Xsubtree=components/packaging 1468941a50dba7e0a82a01cb938338041f028ef9 c16053e90143cd8a9a559b749407d938f0cb4456
```
Adds support for packaging for Ubuntu Artful (17.10)
Also relates to: https://github.com/docker/for-linux/issues/141
=> [17.11] Add Ubuntu Artful (17.10)

components/engine/hack/dockerfile/install-binaries.sh
To address:
* https://github.com/moby/moby/issues/35349 containerd binaries no longer static
Backport fix:
* https://github.com/moby/moby/pull/35350 Add containerd static compile
With cherry-pick of git commit https://github.com/moby/moby/pull/35350/commits/007db06:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 007db06
```
cherry-pick went in clean
=> [17.11] backport Add containerd static compile

components/engine/daemon/cluster/swarm.go
backport:
* moby/moby#35388 cluster: avoid recursive readlock on swarm info
with cherry-pick of git commit https://github.com/moby/moby/pull/35388/commits/ee1be71:
```
$ git cherry-pick -s -x -Xsubtree=components/engine ee1be71
```
no conflicts
=> [17.11]  cluster: avoid recursive readlock on swarm info

components/engine/builder/dockerfile/builder.go
Backport of https://github.com/moby/moby/issues/35391 for 17.11  (addresses https://github.com/moby/moby/issues/35391 for 17.11)
git cherry-pick -s -S -x -Xsubtree=components/engine c6703b722e1c0914342d61ca6af77aea93150873
(cherry picked from commit c6703b722e1c0914342d61ca6af77aea93150873)
ping @tonistiigi @andrewhsu
=> [17.11] builder: fix long stream sync

components/engine/oci/defaults.go
Backport of https://github.com/moby/moby/pull/35399 for Docker 17.11
git cherry-pick -s -S -x -Xsubtree=components/engine a21ecdf3c8a343a7c94e4c4d01b178c87ca7aaa1
This is writeable, and can be used to remove devices. Containers do
not need to know about scsi devices.
(cherry picked from commit a21ecdf3c8a343a7c94e4c4d01b178c87ca7aaa1)
=> [17.11] Add /proc/scsi to masked paths

components/engine/daemon/info_unix.go, components/engine/libcontainerd/client_daemon.go, components/engine/libcontainerd/client_local_windows.go, components/engine/libcontainerd/types.go
Backport of https://github.com/moby/moby/pull/35389 for 17.11
git cherry-pick -s -S -x -Xsubtree=components/engine fec2b144feaaa18998ec2ed34c9bc843c4c29abd
The `docker info` code was shelling out to obtain the version of containerd (using the `--version` flag).
Parsing the output of this version string is error-prone, and not needed, as the containerd API can return the version.
This patch adds a `Version()` method to the containerd Client interface, and uses this to get the containerd version.
(cherry picked from commit fec2b144feaaa18998ec2ed34c9bc843c4c29abd)
ping @mlaventure @gtardif PTAL
=> [17.11] Use containerd API to get version

components/engine/builder/dockerfile/imagecontext.go, components/engine/daemon/create.go, components/engine/integration-cli/docker_api_build_test.go
backport:
* https://github.com/moby/moby/pull/35419 Set OS on scratch image and prevent panic if empty
with cherry-pick of https://github.com/moby/moby/pull/35419/commits/a97817b673cbd3bfaf6e752282c4992ac43ff594:
```
$ git cherry-pick -s -x -Xsubtree=components/engine a97817b
[scra c2888f5973] Set OS on scratch image and prevent panic if empty
Author: John Stephens <johnstep@docker.com>
Date: Mon Nov 6 18:21:10 2017 -0800
3 files changed, 39 insertions(+), 2 deletions(-)
```
clean cherry-pick
=> [17.11] Set OS on scratch image and prevent panic if empty

CHANGELOG.md
There's a typo in one of the links:
docker/cli#598 points to https://github.com/docker/cli/pull/698, which does not exist.
ping @andrewhsu This should also be fixed in the release notes.
=> [17.10] Fix broken link in changelog

components/engine/integration/image/import_test.go, components/engine/internal/testutil/helpers.go, components/engine/vendor.conf, components/engine/vendor/github.com/vbatts/tar-split/README.md, components/engine/vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
backport:
* https://github.com/moby/moby/pull/35424 vendor: update to github.com/vbatts/tar-split@v0.10.2
with cherry-pick of https://github.com/moby/moby/pull/35424/commits/e0ff7cc https://github.com/moby/moby/pull/35424/commits/2f8d3e1 https://github.com/moby/moby/pull/35424/commits/0a13f82
```
$ git cherry-pick -s -x -Xsubtree=components/engine e0ff7cc 2f8d3e1 0a13f82
[tar b25cbcb9af] vendor: update to github.com/vbatts/tar-split@v0.10.2
Author: Aleksa Sarai <asarai@suse.de>
Date: Wed Nov 8 02:50:52 2017 +1100
3 files changed, 31 insertions(+), 17 deletions(-)
[tar 4cd44b4bf2] internal: testutil: add DevZero helper
Author: Aleksa Sarai <asarai@suse.de>
Date: Wed Nov 8 03:29:49 2017 +1100
1 file changed, 14 insertions(+)
[tar ff01ab4a0a] image: add import test for CVE-2017-14992
Author: …
```
=> [17.11] vendor: update to github.com/vbatts/tar-split@v0.10.2

components/engine/integration-cli/docker_cli_daemon_test.go, components/engine/integration-cli/docker_cli_pull_test.go
```
git cherry-pick -x -s -Xsubtree="components/engine" 5739ba1b918402b8eda748ac2f5dd7ce00f2e69f
```
Relates to: https://github.com/moby/moby/pull/34837
This test tries to pull all the tags in the busybox repo and looks to see
if there were more than two images pulled. This was failing on
p/z due to the recent change to manifest lists, where one of the busybox
tags didn't have a p/z manifest in it's manifest list.
This error seems fine to me, so I changed the test to see if pull fails,
it fails with the "manifest not found" error.
Also switched from busybox -> alpine, because it has significantly less tags,
and the images are close in size.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>
(cherry picked from commit …
=> [17.09] fix p/z HubPullSuite tests

components/engine/integration-cli/docker_api_exec_test.go, components/engine/libcontainerd/client_daemon.go, components/engine/libcontainerd/client_daemon_linux.go
```
git cherry-pick -x -s -Xsubtree="components/engine" 6c4ce7cb6c62fb82ed2db1d4ee3a02bc5148cdee
```
Originally from: https://github.com/moby/moby/pull/35484
=> [17.11] libcontainerd: fix leaking container/exec state

components/engine/oci/defaults.go
Backport of https://github.com/moby/moby/pull/35399 for Docker 17.09
git cherry-pick -s -S -x -Xsubtree=components/engine a21ecdf3c8a343a7c94e4c4d01b178c87ca7aaa1
This is writeable, and can be used to remove devices. Containers do
not need to know about scsi devices.
(cherry picked from commit a21ecdf3c8a343a7c94e4c4d01b178c87ca7aaa1)
=> [17.09] Add /proc/scsi to masked paths

components/engine/integration/image/import_test.go, components/engine/internal/testutil/helpers.go, components/engine/vendor.conf, components/engine/vendor/github.com/vbatts/tar-split/README.md, components/engine/vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
backport:
* https://github.com/moby/moby/pull/35424 vendor: update to github.com/vbatts/tar-split@v0.10.2
with cherry-pick of https://github.com/moby/moby/pull/35424/commits/e0ff7cc https://github.com/moby/moby/pull/35424/commits/2f8d3e1 https://github.com/moby/moby/pull/35424/commits/0a13f82
```
$ git cherry-pick -s -x -Xsubtree=components/engine e0ff7cc 2f8d3e1 0a13f82
[tar b25cbcb9af] vendor: update to github.com/vbatts/tar-split@v0.10.2
Author: Aleksa Sarai <asarai@suse.de>
Date: Wed Nov 8 02:50:52 2017 +1100
3 files changed, 31 insertions(+), 17 deletions(-)
[tar 4cd44b4bf2] internal: testutil: add DevZero helper
Author: Aleksa Sarai <asarai@suse.de>
Date: Wed Nov 8 03:29:49 2017 +1100
1 file changed, 14 insertions(+)
[tar ff01ab4a0a] image: add import test for CVE-2017-14992
Author: …
```
=> [17.09] vendor: update to github.com/vbatts/tar-split@v0.10.2

components/engine/integration-cli/docker_api_exec_test.go, components/engine/libcontainerd/client_linux.go, components/engine/libcontainerd/container_unix.go, components/engine/libcontainerd/process_unix.go
Port of the fix:
- moby/moby#35484 libcontainerd: fix leaking container/exec state
for docker/release-tracking#182
@thaJeztah
=> [17.09] libcontainerd: fix leaking container/exec state

components/engine/integration-cli/docker_cli_events_unix_test.go
seeing lots of [failures](https://jenkins.dockerproject.org/job/docker-ce-pr-s390x/173/execution/node/243/log/?consoleFull) on s390x even though the same test passes for x86_64 and ppc64le:
```
FAIL: docker_cli_events_unix_test.go:81: DockerSuite.TestEventsOOMDisableTrue
docker_cli_events_unix_test.go:126:
...
/go/src/github.com/docker/docker/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
... Error: at cli.go:33 - 
Command:  /usr/local/cli/docker kill oomTrue
ExitCode: 1
Error:    exit status 1
Stdout:   
Stderr:   Error response from daemon: Cannot kill container: oomTrue: Container 4979020323f1a54da9f08c5b40c276b9ffcfe982722f5f2432f591af630a2c73 is not running
Failures:
ExitCode was 1 expected 0 …
```
=> [17.09] Avoid failing the test if container is already stopped

components/engine/distribution/pull_v2.go, components/engine/distribution/pull_v2_unix.go, components/engine/distribution/pull_v2_windows.go
Backport fix:
- https://github.com/moby/moby/pull/35090
- https://github.com/moby/moby/pull/35117
with cherry pick of https://github.com/moby/moby/commit/38aef56e1fcb8ea318df98c89cf002267b88a136 and https://github.com/moby/moby/commit/8ed8f4a71d7e1a936fa077b4348b7375c81746a6:
```
git cherry-pick -s -x -Xsubtree=components/engine 38aef5
git cherry-pick -s -x -Xsubtree=components/engine 8ed8f4
```
Conflict with `pull_v2_windows.go` in https://github.com/moby/moby/commit/8ed8f4a71d7e1a936fa077b4348b7375c81746a6 resolved by reverting back to detecting the OS the previous way (before it was supplied as a parameter).
=> [17.09] Backport version fix for Windows manifest lists

components/engine/daemon/cluster/swarm.go
Backport of https://github.com/moby/moby/pull/35388 for 17.09
(cherry picked from commit ee1be71e9dc52db8a7ac951ba96f18a5c894806a)
ping @tonistiigi PTAL
=> [17.09] cluster: avoid recursive readlock on swarm info

components/engine/pkg/chrootarchive/chroot_linux.go
backport of https://github.com/moby/moby/pull/35217 for 17.09
(cherry picked from commit 5ede64d63fec0b9d4cf921b6f8fb946e65287538)
With `rprivate` there exists a race where a reference to a mount has
propagated to the new namespace, when `rprivate` is set the parent
namespace is not able to remove the mount due to that reference.
With `rslave` unmounts will propagate correctly into the namespace and
prevent the sort of transient errors that are possible with `rprivate`.
This is a similar fix to https://github.com/opencontainers/runc/pull/1500/commits/117c92745bd098bf05a69489b7b78cac6364e1d0
ping @cpuguy83 @kolyshkin
=> [17.09] Use rslave instead of rprivate in chrootarchive

components/engine/builder/dockerfile/parser/parser.go, components/engine/builder/dockerfile/parser/parser_test.go
back port of https://github.com/moby/moby/pull/35004 for 17.09
(cherry picked from commit 2fd736ac10c1c46d1001373d887cb99b3d8ee824)
Commit 8d1ae76dcbbb73d8e20c6a14a7d3fe2410b95f55 added
deprecation warnings for empty continuation lines,
but also treated comment-only lines as empty.
This patch distinguishes empty continuation lines
from comment-only lines, and only outputs warnings
for the former.
=> [17.09] Warn on empty continuation lines only, not for comments

components/engine/daemon/daemon_unix.go
back port of https://github.com/moby/moby/pull/35172 for 17.09 
(cherry picked from commit c6a2044497e0e1ff61350859c8572a2c31c17ced)
83c2152de503012195bd26069fd8fbd2dea4b32f sets the kernel param for
fs.may_detach_mounts, but this is not neccessary for the daemon to
operate. Instead of erroring out (and thus aborting startup) just log
the error.
ping @cpuguy83 PTAL
=> [17.09] Don't abort when setting may_detach_mounts

components/engine/daemon/cluster/executor/container/controller.go, components/engine/daemon/daemon_test.go, components/engine/daemon/errors.go, components/engine/daemon/network.go, components/engine/integration-cli/docker_cli_netmode_test.go
Cherry-pick of https://github.com/moby/moby/pull/35634 (https://github.com/moby/moby/pull/35634/commits/51cea0a53c2fd36832277402e9faac81bfb4abd4) for 17.09
```
git checkout -b 17.09-backport-fix-net-not-found upstream/17.09
git cherry-pick -s -S -x -Xsubtree=components/engine 51cea0a53c2fd36832277402e9faac81bfb4abd4
```
Conflicts in:
both modified:   components/engine/daemon/daemon_test.go
both modified:   components/engine/daemon/network.go
Due to https://github.com/moby/moby/commit/e52001c56e12e4fc63fb5d89ef919295d6ddd5d5 not being included in 17.09
I fixed the conflicts in `components/engine/daemon/network.go` by moving the error fix from `FindNetwork()` to `GetNetworkByID()`
The error type libnetwork.ErrNoSuchNetwork is used in the controller
to retry the network creation as a managed …
=> [17.09] Restore error type in FindNetwork

components/engine/daemon/daemon_linux_test.go, components/engine/daemon/oci_linux.go
Backport of 
- https://github.com/moby/moby/pull/35316 Fix honoring tmpfs-size for user /dev/shm mount
```
$ git checkout 17.09
Branch 17.09 set up to track remote branch 17.09 from origin.
Switched to a new branch '17.09'
$ git checkout -b backport-353516-17.09
Switched to a new branch 'backport-353516-17.09'
$ git cherry-pick -s -x -Xsubtree=components/engine  31d30a985d99a0eef 2e0a98b605fa27
error: could not apply 31d30a985d... Fix user mount /dev/shm size
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
$ vim components/engine/daemon/oci_linux.go
$ git add components/engine/daemon/oci_linux.go
$ git cherry-pick --continue 
[backport-353516-17.09 15e5af3a07] Fix user mount …
```
=> [17.09] Fix honoring tmpfs-size for user /dev/shm mount

components/engine/daemon/graphdriver/devmapper/deviceset.go, components/engine/daemon/graphdriver/devmapper/devmapper_test.go, components/engine/daemon/graphdriver/devmapper/driver.go
back port of https://github.com/moby/moby/pull/34573 for 17.09
```
git cherry-pick -s -S -x -Xsubtree=components/engine 92e45b81e0a8b68d9567a2068247460a1ba59600
git cherry-pick -s -S -x -Xsubtree=components/engine 1af8ea681fba1935c60c11edbbe19b894c9b286f
```
ping @kolyshkin PTAL
=> [17.09] backport dm dos prevention remove mountpoint

components/cli/vendor.conf, components/cli/vendor/github.com/docker/docker/client/client.go, components/engine/client/client.go, components/engine/client/client_test.go
Cherry-pick of https://github.com/moby/moby/pull/35008 (https://github.com/moby/moby/pull/35008/commits/4b6ec10b07c14e7fff1cc51156b6d954147f826f) into components/engine and components/cli;
```bash
git fetch https://github.com/moby/moby.git master:moby-master
git fetch https://github.com/docker/cli.git master:cli-master
git checkout -b 17.09-backport-cli-version upstream/17.09
git cherry-pick -s -S -x -Xsubtree=components/engine 4b6ec10b07c14e7fff1cc51156b6d954147f826f
git format-patch -1 4b6ec10b07c14e7fff1cc51156b6d954147f826f
0001-Fix-version-comparison-when-negotiating-the-the-API-.patch
git am -s -S \
--directory=components/cli/vendor/github.com/docker/docker \
--exclude=components/cli/vendor/github.com/docker/docker/client/client_test.go \ …
```
=> [17.09] Fix version comparison when negotiating the the API version

components/cli/cli/command/cli.go, components/cli/cli/command/cli_test.go
cherry-pick of https://github.com/docker/cli/pull/546 for 17.09
(cherry picked from commit e828efa4abb202ef16e8def72d250d13e8e5af0e)
Refactor to support testing
Also add tests
=> [17.09] Set APIVersion on the client, even when Ping fails

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/trust_server_test.go
Seeing [failures](https://jenkins.dockerproject.org/job/docker-ce-pr/420/execution/node/912/log/?consoleFull) in `DockerTrustSuite`: 
```
FAIL: docker_cli_build_test.go:4213: DockerTrustSuite.TestTrustedBuildTagFromReleasesRole
FAIL: docker_cli_build_test.go:4244: DockerTrustSuite.TestTrustedBuildTagIgnoresOtherDelegationRoles
FAIL: docker_cli_create_test.go:293: DockerTrustSuite.TestTrustedCreate
FAIL: docker_cli_create_test.go:329: DockerTrustSuite.TestTrustedCreateFromBadTrustServer
FAIL: docker_cli_create_test.go:319: DockerTrustSuite.TestTrustedIsolatedCreate
FAIL: docker_cli_pull_trusted_test.go:25: DockerTrustSuite.TestTrustedIsolatedPull
FAIL: docker_cli_pull_trusted_test.go:85: DockerTrustSuite.TestTrustedOfflinePull
FAIL: docker_cli_pull_trusted_test.go:14: …
```
=> [17.12] skip DockerTrustSuite tests for 17.12

components/packaging/rpm/fedora-27/docker-ce.spec
```
git cherry-pick -x -s -Xsubtree="components/packaging" dcd681da54f2c2b2286cc09d053dd6cb865d3f98
```
Relates to an upgrade in `rpm` to `14.4.0`, where missing build-ids now
cause builds to self-terminate. May be needed in other distros if/when
the `rpm` package is updated in those repos.
(cherry picked from commit dcd681da54f2c2b2286cc09d053dd6cb865d3f98)
=> [17.12] Do not terminate on missing build-ids

components/engine/docs/api/version-history.md
backport of https://github.com/moby/moby/pull/35724 (https://github.com/moby/moby/pull/35724/commits/8a9d926b553345be530ddc51374c9817fcbea784) for 17.12
(cherry picked from commit 8a9d926b553345be530ddc51374c9817fcbea784)
```
git checkout -b 17.12-backport-update-api-changelog upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 8a9d926b553345be530ddc51374c9817fcbea784
```
no conflicts
=> [17.12] Update API version-history for 1.35

components/engine/vendor.conf, components/engine/vendor/archive/tar/common.go, components/engine/vendor/archive/tar/writer.go
Backport of https://github.com/moby/moby/pull/35728 (https://github.com/moby/moby/pull/35728/commits/13954b0a6282d919c91626a23967377c19ee7aa2) for 17.12
```
git checkout -b 17.12-backport-vendor-archive upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 13954b0a6282d919c91626a23967377c19ee7aa2
```
no conflicts
=> [17.12] vendor: update archive/tar

components/packaging/static/Makefile
backport:
* https://github.com/docker/docker-ce-packaging/pull/70
VERSION file does not exist anymore for moby/moby so we need to
compensate
(cherry picked from commit c411321b8870101c227b03e64930260984c862fd)
=> [17.12] Pass VERSION to engine static builds

components/cli/cli/compose/convert/compose.go, components/cli/cli/compose/convert/compose_test.go, components/cli/cli/compose/convert/service.go, components/cli/cli/compose/convert/service_test.go
Backport of https://github.com/docker/cli/pull/743 for 17.12
(cherry picked from commit 9da2602f3899347cd903258c98499123ff08a78b)
no conflicts
ping @vdemeester @dnephin @andrewhsu PTAL
=> [17.12] Fix external networks

components/engine/vendor.conf, components/engine/vendor/github.com/Graylog2/go-gelf/gelf/tcpreader.go, components/engine/vendor/github.com/Graylog2/go-gelf/gelf/tcpwriter.go, components/engine/vendor/github.com/Graylog2/go-gelf/gelf/writer.go
Backport of https://github.com/moby/moby/pull/35765 for 17.12
```
git checkout -b 17.12-backport-35613-update-go-gelf-v2-for-bugfix upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 5bc11021250e39e71ca9edf62ce5c33f15c3756f
git cherry-pick -s -S -x -Xsubtree=components/engine f9f3c49302fc80e586e3cb10af43114929556b47
```
No conflicts
ping @anusha-ragunathan @andrewhsu @cpuguy83 PTAL
=> [17.12] backport 35613 update go gelf v2 for bugfix

components/cli/contrib/completion/bash/docker, components/cli/contrib/completion/zsh/_docker, components/cli/docs/deprecated.md, components/cli/docs/reference/commandline/dockerd.md, components/cli/man/dockerd.8.md, components/engine/cmd/dockerd/config.go, components/engine/cmd/dockerd/daemon.go, components/engine/cmd/dockerd/daemon_unix_test.go, components/engine/integration-cli/docker_cli_logout_test.go, components/engine/integration-cli/docker_cli_pull_test.go, components/engine/integration-cli/docker_cli_v2_only_test.go
Backport of https://github.com/moby/moby/pull/35751 and https://github.com/docker/cli/pull/747 for 17.12
No conflicts
Interacting with v1 registries was deprecated in Docker 1.8.3, disabled by default
in Docker 17.06, and scheduled for removal in Docker 17.12.
This patch disallows enabling V1 registry through the `--disable-legacy-registry`
option, and the `"disable-legacy-registry": false` option in the daemon configuration
file. The actual V1 registry code is still in place, and will be removed separately.
With this patch applied:
$ dockerd --disable-legacy-registry=false
ERROR: The '--disable-legacy-registry' flag has been removed. Interacting with legacy (v1) registries is no longer supported
Or, when setting through the `daemon.json` configuration file
$ mkdir -p /etc/docker/
$ echo …
=> [17.12] Disallow using legacy (V1) registries

components/cli/docs/reference/commandline/dockerd.md, components/cli/docs/reference/commandline/service_create.md, components/cli/docs/reference/commandline/service_update.md
cherry-picks of;
- https://github.com/docker/cli/pull/746 "Correct references to --publish long syntax in docs"
- https://github.com/docker/cli/pull/748 "Fix anchors to "Storage driver options" "
=> [17.12] docs cherry picks

CHANGELOG.md
This following line is a vendoring change let me know if it should be removed.
```
Update Graylog2/go-gelf [moby/moby#35765](https://github.com/moby/moby/pull/35765)
```
Omitted https://github.com/docker/docker-ce/pull/352 from the docs
Happy to add it if it belongs
=> [17.12] update changelog for 17.12.0-ce-rc3

components/cli/docs/deprecated.md, components/engine/daemon/image.go, components/engine/integration-cli/docker_cli_create_test.go, components/engine/integration-cli/docker_cli_tag_test.go
backport for 17.12 of:
* https://github.com/moby/moby/pull/35790 Remove support for referencing images by 'repository:shortid'
* https://github.com/docker/cli/pull/753 Updated deprecation status for "repository:shortid"
```
git checkout -b 17.12-backport-image-shortid upstream/17.12  
git cherry-pick -s -S -x -Xsubtree=components/engine a942c92dd77aff229680c7ae2a6de27687527b8a
git cherry-pick -s -S -x -Xsubtree=components/cli 1a21ca12a62ec78af55b71a04b1ca606ef6771fe
```
no conflicts
=> [17.12] Remove support for referencing images by 'repository:shortid'

components/cli/contrib/completion/bash/docker, components/cli/contrib/completion/zsh/_docker, components/cli/docs/reference/commandline/run.md
Cherry-picks for 17.12 of:
- https://github.com/docker/cli/pull/751/commits/db05d8ad79e34e8096f31585fe9ffe0ce18f98d8 (https://github.com/docker/cli/pull/751) ("Fix error in zsh completion script for docker exec")
- https://github.com/docker/cli/pull/754/commits/43217d733205b0694f791e7326bfed6d13b645f0 (https://github.com/docker/cli/pull/754) (Fix "on-failure" restart policy being documented as "failure")
- https://github.com/docker/cli/pull/749/commits/8ec80eec672b93be03843412f195fae477e81c4a (https://github.com/docker/cli/pull/749) (Add support for generic resources to bash completion)
- https://github.com/docker/cli/pull/713/commits/a2d0b6e122021cfac87a99a46d3d02339552d281 (https://github.com/docker/cli/pull/713) (Fix Bash autocompletion works incorrect with inspect)
```
git checkout -b …
```
=> [17.12] backport docs and completion

components/engine/pkg/tarsum/fileinfosums.go
Backport of https://github.com/moby/moby/pull/35793 for 17.12
```
git checkout -b 17.12-backport-33107 upstream/17.12  
git cherry-pick -s -S -x -Xsubtree=components/engine 7caa30e8937b65ad9fd61a8b811bba470d22809f
```
no conflicts
(cherry picked from commit 7caa30e8937b65ad9fd61a8b811bba470d22809f)
=> [17.12] Windows: Case-insensitive filename matching against builder cache

components/engine/daemon/kill.go, components/engine/libcontainerd/client_daemon.go
Backport of https://github.com/moby/moby/pull/35809 for 17.12
```bash
git checkout -b 17.12-backport-fix_container_zombies upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine e55bead518e4c72cdecf7de2e49db6c477cb58eb
git cherry-pick -s -S -x -Xsubtree=components/engine 647cec4324186faa3183bd6a7bc72a032a86c8c9
```
no conflicts
ping @vieux @cpuguy83 @vdemeester
=> [17.12] backport fix container zombies

components/engine/daemon/daemon.go, components/engine/integration/container/restart_test.go
```
git cherry-pick -x -s -Xsubtree="components/engine" e69127bd5ba4dcf8ae1f248db93a95795eb75b93
```
When the containerd 1.0 runtime changes were made, we inadvertantly
removed the functionality where any running containers are killed on
startup when not using live-restore.
This change restores that behavior.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit e69127bd5ba4dcf8ae1f248db93a95795eb75b93)
=> [17.12] Ensure containers are stopped on daemon startup

components/engine/daemon/daemon.go, components/engine/integration-cli/docker_cli_daemon_test.go, components/engine/plugin/executor/containerd/containerd.go
Cherry picked from: https://github.com/moby/moby/pull/35812
```
git cherry-pick -x -s -Xsubtree="components/engine" 521e7eba86df25857647b93f13e5366c554e9d63
```
Follow the conventions for namespace naming set out by other projects,
such as linuxkit and cri-containerd. Typically, they are some sort of
host name, with a subdomain describing functionality of the namespace.
In the case of linuxkit, services are launched in `services.linuxkit`.
In cri-containerd, pods are launched in `k8s.io`, making it clear that
these are from kubernetes.
Signed-off-by: Stephen J Day <stephen.day@docker.com>
(cherry picked from commit 521e7eba86df25857647b93f13e5366c554e9d63)
=> [17.12] daemon, plugin: follow containerd namespace conventions

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/trust_server_test.go
Seeing [failures](https://jenkins.dockerproject.org/job/docker-ce-pr/420/execution/node/912/log/?consoleFull) in `DockerTrustSuite`: 
```
...
FAIL: docker_cli_build_test.go:4223: DockerTrustSuite.TestTrustedBuildTagFromReleasesRole
FAIL: docker_cli_build_test.go:4254: DockerTrustSuite.TestTrustedBuildTagIgnoresOtherDelegationRoles
FAIL: docker_cli_create_test.go:295: DockerTrustSuite.TestTrustedCreate
FAIL: docker_cli_create_test.go:331: DockerTrustSuite.TestTrustedCreateFromBadTrustServer
FAIL: docker_cli_create_test.go:321: DockerTrustSuite.TestTrustedIsolatedCreate
FAIL: docker_cli_pull_trusted_test.go:25: DockerTrustSuite.TestTrustedIsolatedPull
FAIL: docker_cli_pull_trusted_test.go:85: DockerTrustSuite.TestTrustedOfflinePull
FAIL: docker_cli_pull_trusted_test.go:14: …
```
=> [18.01] skip DockerTrustSuite tests for 18.01

components/engine/api/common.go, components/engine/api/swagger.yaml, components/engine/docs/api/version-history.md
There were no changes made yet to the API, so no need to bump the API version for this release
This reverts commit c1e982f2ee85580687e2d355af3ca444ada14d01 (https://github.com/moby/moby/pull/35738)
```
git checkout -b 18.01-revert-api-bump upstream/18.01
git revert -s -S -Xsubtree=components/engine c1e982f2ee85580687e2d355af3ca444ada14d01
```
=> [18.01] Revert "Bump API version to 1.36"

components/engine/contrib/download-frozen-image-v2.sh, components/engine/hack/make/.detect-daemon-osarch
building aarch64 static binaries with docker-ce 18.01 code is failing with error:
```
00:09:54 error: unknown manifest mediaType (library/buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251): 'application/vnd.docker.distribution.manifest.list.v2+json'
00:09:56 The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 	busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 	debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 	hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c' returned a non-zero code: 1
00:09:56 …
```
=> [18.01] Download support of images with multi-arch manifest

components/cli/docs/yaml/yaml.go
backport fix:
* https://github.com/docker/cli/pull/802 Fix docs YAML generation setting "kubernetes" for "swarm"
with cherry-pick of git commit https://github.com/docker/cli/pull/802/commits/6be06a3:
```
$ git cherry-pick -s -x -Xsubtree=components/cli 6be06a3
```
no conflicts.
=> [18.01] Fix docs YAML generation setting "kubernetes" for "swarm"

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/trust_server_test.go
Seeing [failures](https://jenkins.dockerproject.org/job/docker-ce/223/execution/node/1003/log/) in `DockerTrustSuite`: 
```
...
FAIL: docker_cli_build_test.go:4223: DockerTrustSuite.TestTrustedBuildTagFromReleasesRole
FAIL: docker_cli_build_test.go:4254: DockerTrustSuite.TestTrustedBuildTagIgnoresOtherDelegationRoles
FAIL: docker_cli_create_test.go:295: DockerTrustSuite.TestTrustedCreate
FAIL: docker_cli_create_test.go:331: DockerTrustSuite.TestTrustedCreateFromBadTrustServer
FAIL: docker_cli_create_test.go:321: DockerTrustSuite.TestTrustedIsolatedCreate
FAIL: docker_cli_pull_trusted_test.go:25: DockerTrustSuite.TestTrustedIsolatedPull
FAIL: docker_cli_pull_trusted_test.go:85: DockerTrustSuite.TestTrustedOfflinePull
FAIL: docker_cli_pull_trusted_test.go:14: …
```
=> [18.02] skip DockerTrustSuite tests for 18.02

components/cli/dockerfiles/Dockerfile.cross, components/cli/dockerfiles/Dockerfile.dev, components/cli/dockerfiles/Dockerfile.lint
cherry-pick of https://github.com/docker/cli/pull/827 for 18.02
```
git checkout -b 18.02-backport-bump-golang-1.9.3 upstream/18.02
git cherry-pick -s -S -x -Xsubtree=components/cli ffc76483226ee1528cab5cf8ea78c0824272cd58
```
no conflicts
=> [18.02] Bump Go to 1.9.3

components/engine/cmd/dockerd/config.go, components/engine/cmd/dockerd/daemon_test.go
backport of https://github.com/moby/moby/pull/36125 for 18.02, no conflicts
Daemon flags that can be specified multiple times use
singlar names for flags, but plural names for the configuration
file.
To make the daemon configuration know how to correlate
the flag with the corresponding configuration option,
`opt.NewNamedListOptsRef()` should be used instead of
`opt.NewListOptsRef()`.
Commit 6702ac590e6148cb3f606388dde93a011cb14931 attempted
to fix the daemon not corresponding the flag with the configuration
file option, but did so by changing the name of the flag
to plural.
This patch reverts that change, and uses `opt.NewNamedListOptsRef()`
instead.
(cherry picked from commit 6e7715d65ba892a47d355e16bf9ad87fb537a2d0)
Signed-off-by: …
=> [18.02] Fix "--node-generic-resource" singular/plural

components/cli/cli/command/stack/cmd.go, components/cli/cmd/docker/docker.go
backport:
* https://github.com/docker/cli/pull/804 Annotate "stack" commands to be "swarm" and "kubernetes"
with cherry-pick of git commit https://github.com/docker/cli/pull/804/commits/93c36eb228f6e85b68dbddd374fc7ed0b07ab28d:
```
$ git cherry-pick -s -x -Xsubtree=component/cli 93c36eb
```
no conflicts
=> [18.02] Annotate "stack" commands to be "swarm" and "kubernetes"

components/engine/libcontainerd/client_daemon.go, components/engine/libcontainerd/remote_daemon.go
Cherry-pick of https://github.com/moby/moby/pull/36173 for 17.12. Also includes https://github.com/moby/moby/pull/35768 (which is just a typo fix) to get a clean cherry-pick
```
git checkout -b 17.12-backport-fix_containerd_crash_spin upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 5c3418e38b9603e8ff582d53c2face57f0f01cce
git cherry-pick -s -S -x -Xsubtree=components/engine 400126f8698233099259da967378c0a76bc3ea31
```
no conflicts
Before this patch, when containerd is restarted (due to a crash, or
kill, whatever), the daemon would keep trying to process the event
stream against the old socket handles. This would lead to a CPU spin due
to the error handling when the client can't connect to containerd.
This change makes sure the containerd remote client is updated for …
=> [17.12] Refresh containerd remotes on containerd restarted

components/engine/daemon/cluster/executor/container/executor.go
Backport of https://github.com/moby/moby/pull/36003 for 17.12 (fixes https://github.com/moby/moby/issues/35941)
```
git checkout -b 17.12-backport-upgrade_fix upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 2d7a50e5855ad0571e76d29cd1ab9f8f3a48433b
git push --set-upstream origin 17.12-backport-upgrade_fix
```
(cherry picked from commit 2d7a50e5855ad0571e76d29cd1ab9f8f3a48433b)
no conflicts
=> [17.12] Fixing ingress network when upgrading from 17.09 to 17.12.

components/engine/libcontainerd/client_daemon.go
backport of https://github.com/moby/moby/pull/35896 for 17.12.x
```
git checkout -b 17.12-backport-fix-namespace-filtering upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 295bb09184fe473933498bb0efb59b8acb124f55
```
No conflicts
The event filter used two separate filter-conditions for "namespace" and "topic". As a result, both events matching "topic" and events matching "namespace" were subscribed to, causing events to be handled both by the "plugin" client, and "container" client.
This patch rewrites the filter to match only if both namespace and topic match.
Thanks to Stephen Day for providing the correct filter :)
(cherry picked from commit 295bb09184fe473933498bb0efb59b8acb124f55)
Signed-off-by: Sebastiaan van …
=> [17.12] Fix event filter filtering on "or"

components/engine/daemon/graphdriver/quota/projectquota.go, components/engine/daemon/graphdriver/vfs/driver.go, components/engine/daemon/graphdriver/vfs/quota_linux.go
back port of https://github.com/moby/moby/pull/35827 for 17.12.x
```
git checkout -b backport-vfs-quota upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 2dd39b7841bdb9968884bbedc5db97ff77d4fe3e
git cherry-pick -s -S -x -Xsubtree=components/engine 1e8a087850aa9f96c5000a3ad90757d2e9c0499f
```
No conclicts
ping @kolyshkin @cpuguy83
=> [17.12] Fix VFS vs quota regression

components/engine/daemon/logger/awslogs/cloudwatchlogs.go, components/engine/daemon/logger/awslogs/cloudwatchlogs_test.go, components/engine/daemon/logger/awslogs/cwlogsiface_mock_test.go
git cherry-pick -s -x -Xsubtree=components/engine ad14dbf1346742f0607d7c28a8ef3d4064f5f9fd
Cherry-pick was clean.
Original PR https://github.com/moby/moby/pull/35726
The previous bytes counter was moved out of scope was not counting the
total number of bytes in the batch. This type encapsulates the counter
and the batch for consideration and code ergonomics.
Signed-off-by: Jacob Vallejo <jakeev@amazon.com>
(cherry picked from commit ad14dbf1346742f0607d7c28a8ef3d4064f5f9fd)
Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>
=> [17.12] awslogs: Use batching type for ergonomics and correct counting

components/engine/daemon/health.go, components/engine/integration/container/health_test.go
Backport of https://github.com/moby/moby/pull/35845 for 17.12.x
```
git checkout -b backport-FIX35843 upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 852a943c773382df09cdda4f29f9e93807523178
git cherry-pick -s -S -x -Xsubtree=components/engine 5be2f2be243a52eb1b051c981bac5442b6e85606
```
no conflicts
=> [17.12] Backport "fix #35843 regression on health check workingdir"

components/packaging/deb/common/rules, components/packaging/rpm/fedora-25/docker-ce.spec, components/packaging/rpm/fedora-26/docker-ce.spec, components/packaging/rpm/fedora-27/docker-ce.spec
This is a backport of https://github.com/docker/docker-ce-packaging/pull/78 to Docker CE 17.12
=> [17.12] Uncomment TasksMax=unlimited for recent distros

components/engine/vendor.conf, components/engine/vendor/github.com/Microsoft/hcsshim/legacy.go
backport of https://github.com/moby/moby/pull/35924 for 17.12
```
git checkout -b 17.12-backport-32838-partial-fix upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 172a442c27ed35778662980809824fdf15a722a6
```
no conflicts
=> [17.12] Vendor Microsoft/hcsshim @ v0.6.8

components/engine/cmd/dockerd/config.go, components/engine/cmd/dockerd/daemon_test.go
backport of https://github.com/moby/moby/pull/35970 and https://github.com/moby/moby/pull/36125 for 17.12
=> [17.12] backport fix plural singular node generic resources

components/cli/cli/command/stack/deploy_composefile.go
Cherry-pick of https://github.com/docker/cli/pull/757 for 17.12.x
```
git checkout -b backport-fix-missing-errors upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/cli a30dd1b6f35541a1ae32df67e7bdd38d0535aab9
```
(no conflicts)
ping @dnephin @vdemeester
=> [17.12] Return errors from client in stack deploy configs

components/engine/libcontainerd/client_daemon.go
back port of https://github.com/moby/moby/pull/35957 for 17.12
```
git checkout -b 17.12-backport-ramdisk upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 54051e9e64185e442e034c7e49a5707459a9eed2
```
no conflicts
=> [17.12] Honor DOCKER_RAMDISK with containerd 1.0

components/engine/api/server/router/network/network_routes.go, components/engine/integration/network/inspect_test.go
Backport of https://github.com/moby/moby/pull/35989 for 17.12
```
git checkout -b 17.12-backport-orca-11380 upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 2e0990f1655d151b741e7f7f78ac55e14398339f
```
(no conflicts)
=> [17.12] fix verbose for partial overlay ID

components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go, components/engine/vendor/github.com/docker/libnetwork/osl/namespace_linux.go
Brings in a cherry pick of https://github.com/docker/libnetwork/commit/76bfcb0eb14686d3c25683df22e14bc1d3b093ef
In sandbox creation we disable IPV6 config. But this causes problem in live-restore case
where all IPV6 configs are wiped out on running container. Hence extra check has been added
take care of this issue.
full diff:
https://github.com/docker/libnetwork/compare/7dd202d11b2078c063fefc614c9fb9e4615da0e1...0ef1f8c94fa85acacf88b9be75ae07de91d0b2a5
which includes these changes:
* https://github.com/docker/libnetwork/pull/2052 [Backport 17.12] watchMiss fixes
* https://github.com/docker/libnetwork/pull/2059 [17.12] Enable IPV6 config on Sandbox creation on live-restore
=> [17.12] bump libnetwork to 0ef1f8c94fa85acacf88b9be75ae07de91d0b2a5

components/engine/daemon/container.go, components/engine/volume/lcow_parser.go, components/engine/volume/linux_parser.go, components/engine/volume/parser.go, components/engine/volume/validate_test.go, components/engine/volume/windows_parser.go
back port of https://github.com/moby/moby/pull/35833 for 17.12
```
git checkout -b 17.12-backport-fix-mount-creation-on-start upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 7cb96ba308dc53824d2203fd343a4a297d17976e
```
no conflicts
Validation of Mounts was only performed on container _creation_, not on
container _start_. As a result, if the host-path no longer existed
when the container was started, a directory was created in the given
location.
This is the wrong behavior, because when using the `Mounts` API, host paths
should never be created, and an error should be produced instead.
This patch adds a validation step on container start, and produces an
error if the host path is not found.
=> [17.12] Re-validate Mounts on container start

components/engine/daemon/cluster/convert/network.go, components/engine/daemon/cluster/convert/network_test.go
Backport of https://github.com/moby/moby/pull/36095 for 17.12
```
git checkout -b 17.12-backport-36083-network-inspect-created-time upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 090c439fb8a863731cc80fcb9932ce5958d8166d
```
(no conflicts)
This fix tries to address the issue raised in 36083 where
`network inspect` does not show Created time if the network is
created in swarm scope.
The issue was that Created was not converted from swarm api.
This fix addresses the issue.
An unit test has been added.
This fix fixes 36083.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
(cherry picked from commit 090c439fb8a863731cc80fcb9932ce5958d8166d)
Please do not send pull requests to this docker/docker-ce repository.
We …
=> [17.12] Fix issue where network inspect does not show Created time in swarm scope

components/engine/daemon/graphdriver/aufs/aufs.go, components/engine/daemon/graphdriver/btrfs/btrfs.go, components/engine/daemon/graphdriver/devmapper/driver.go, components/engine/daemon/graphdriver/overlay/overlay.go, components/engine/daemon/graphdriver/overlay2/overlay.go, components/engine/daemon/graphdriver/zfs/zfs.go
Backport of moby/moby#36047
```
git cherry-pick -s -S -x -Xsubtree=components/engine 9803272f2db84df7955b16c0d847ad72cdc494d1
```
----
The idea behind making the graphdrivers private is to prevent leaking
mounts into other namespaces.
Unfortunately this is not really what happens.
There is one case where this does work, and that is when the namespace
was created before the daemon's namespace.
However with systemd each system servie winds up with it's own mount
namespace. This causes a race betwen daemon startup and other system
services as to if the mount is actually private.
This also means there is a negative impact when other system services
are started while the daemon is running.
Basically there are too many things that the daemon does not have
control over (nor should it) to be able …
=> [17.12] Do not make graphdriver homes private mounts.

components/engine/daemon/daemon_unix.go
Cherry-pick moby/moby#36096
```
git cherry-pick -s -x -Xsubtree=components/engine  a510192b86e7eb1e1112f3f625d80687fdec6578
```
---
This change sets an explicit mount propagation for the daemon root.
This is useful for people who need to bind mount the docker daemon root
into a container.
Since bind mounting the daemon root should only ever happen with at
least `rlsave` propagation (to prevent the container from holding
references to mounts making it impossible for the daemon to clean up its
resources), we should make sure the user is actually able to this.
Most modern systems have shared root (`/`) propagation by default
already, however there are some cases where this may not be so
(e.g. potentially docker-in-docker scenarios, but also other cases).
So this just gives the daemon a …
=> [17.12] Set daemon root to use shared propagation

components/engine/daemon/oci_linux.go, components/engine/daemon/volumes.go, components/engine/daemon/volumes_linux.go, components/engine/daemon/volumes_linux_test.go, components/engine/daemon/volumes_windows.go, components/engine/integration/container/mounts_linux_test.go
Backports moby/moby#36055
```
git cherry-pick -s -x -Xsubtree=components/engine 589a0afa8cbe39b6512662fd1705873e2d236dd0
```
----
By default, if a user requests a bind mount it uses private propagation.
When the source path is a path within the daemon root this, along with
some other propagation values that the user can use, causes issues when
the daemon tries to remove a mountpoint because a container will then
have a private reference to that mount which prevents removal.
Unmouting with MNT_DETATCH can help this scenario on newer kernels, but
ultimately this is just covering up the problem and doesn't actually
free up the underlying resources until all references are destroyed.
This change does essentially 2 things:
1. Change the default propagation when unspecified to `rslave` when the …
=> [17.12] Use rslave propagation for mounts from daemon root

components/engine/api/swagger.yaml, components/engine/api/types/swarm/task.go
back port of https://github.com/moby/moby/pull/36146 for 17.12
```
git checkout -b 17.12-backport-36142-TaskState upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine a40687f5ac7df27bc6c6c3a6f69513a397a1a05a
```
no conclicts
This fix tries to address the issue raised in 36142 where
there are discrepancies between Swarm API and swagger.yaml.
This fix adds two recently added state `REMOVE` and `ORPHANED` to TaskState.
This fix fixes 36142.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
(cherry picked from commit a40687f5ac7df27bc6c6c3a6f69513a397a1a05a)
=> [17.12] Add `REMOVE` and `ORPHANED` to TaskState

components/engine/daemon/changes.go, components/engine/daemon/daemon.go, components/engine/daemon/delete.go, components/engine/daemon/inspect.go, components/engine/daemon/inspect_test.go, components/engine/daemon/oci_windows.go
*(this is a replacement for https://github.com/docker/docker-ce/pull/424)*
back port of moby/moby#36160 and moby/moby#36242 for 17.12
```
git checkout -b 17.12-backport-layer-not-retained upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine e9b9e4ace294230c6b8eb010eda564a2541c4564
git cherry-pick -s -S -x -Xsubtree=components/engine 195893d38160c0893e326b8674e05ef6714aeaa4
```
Second commit is modified to use `systemError` instead of `errdefs.System(err)` (as https://github.com/moby/moby/commit/87a12421a94faac294079bebc97c8abb4180dde5 is not backported).
=> [17.12] backport layer not retained

components/engine/integration-cli/docker_cli_attach_unix_test.go
seeing [errors](https://jenkins.dockerproject.org/job/docker-ce-pr-ppc64le/381/execution/node/402/log/) in the 18.03 codebase:
```
panic: DockerSuite.TestAttachAfterDetach test timed out after 5m0s [recovered]
panic: DockerSuite.TestAttachAfterDetach test timed out after 5m0s
```
backport of:
* https://github.com/moby/moby/pull/36363 Fix TestAttachAfterDetach to work with latest client
with cherry-pick:
```
$ git cherry-pick -s -x 847b610
```
no conflicts
=> [18.03] Fix TestAttachAfterDetach to work with latest client

components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_pull_trusted_test.go, components/engine/integration-cli/docker_cli_push_test.go, components/engine/integration-cli/trust_server_test.go
Seeing [failures](https://jenkins.dockerproject.org/job/docker-ce/252/execution/node/976/log/) in `DockerTrustSuite`: 
```
...
FAIL: docker_cli_build_test.go:4224: DockerTrustSuite.TestTrustedBuildTagFromReleasesRole
FAIL: docker_cli_build_test.go:4255: DockerTrustSuite.TestTrustedBuildTagIgnoresOtherDelegationRoles
FAIL: docker_cli_create_test.go:295: DockerTrustSuite.TestTrustedCreate
FAIL: docker_cli_create_test.go:331: DockerTrustSuite.TestTrustedCreateFromBadTrustServer
FAIL: docker_cli_create_test.go:321: DockerTrustSuite.TestTrustedIsolatedCreate
FAIL: docker_cli_pull_trusted_test.go:25: DockerTrustSuite.TestTrustedIsolatedPull
FAIL: docker_cli_pull_trusted_test.go:85: DockerTrustSuite.TestTrustedOfflinePull
FAIL: docker_cli_pull_trusted_test.go:14: DockerTrustSuite.TestTrustedPull …
```
=> [18.03] skip DockerTrustSuite tests for 18.03

components/cli/cli/command/container/client_test.go, components/cli/cli/command/container/cp_test.go, components/cli/cli/command/container/opts.go, components/cli/cli/command/container/run_test.go, components/engine/integration-cli/docker_cli_build_test.go, components/engine/integration-cli/docker_cli_cp_from_container_test.go, components/engine/integration-cli/docker_cli_cp_to_container_test.go, components/engine/integration-cli/docker_cli_cp_utils_test.go, components/engine/integration/container/copy_test.go
Fixes some failing tests on engine; more commits can be added to this, but we can merge at any point.
backport of:
* moby/moby#36427 Clean some docker_cli_build_tests that are cli-only
* https://github.com/docker/cli/pull/907 Add more container cp tests
* https://github.com/moby/moby/pull/36434 Migrate some container copy tests to integration
Also cherry-pick #446 👼
=> [18.03] Fixes tests to have the ci green

components/cli/cli/command/config/create.go, components/cli/cli/command/config/create_test.go, components/cli/cli/command/secret/create.go, components/cli/cli/command/secret/create_test.go, components/cli/docs/reference/commandline/secret_create.md
cherry-pick of https://github.com/docker/cli/pull/896/commits/d11b5ccdfa4df102c1783afca28de25323e6f520 (https://github.com/docker/cli/pull/896) for 18.03
```
git checkout -b 18.03-backport-templated-configs-secrets upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/cli d11b5ccdfa4df102c1783afca28de25323e6f520
git push --set-upstream origin 18.03-backport-templated-configs-secrets
```
no conflicts
=> [18.03] Add --template-driver option for secrets/configs

components/cli/vendor.conf, components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/dispatcher/dispatcher.go
brings in the following changes:
* https://github.com/docker/swarmkit/pull/2432 scheduler: Adding plugin filter unit test for bind mount
* https://github.com/docker/swarmkit/pull/2501 Redact registry auth token from swarm-rafttool
* https://github.com/docker/swarmkit/pull/2518 Revert "[manager/dispatcher] Synchronize Dispatcher.Stop() with incoming rpcs."
* https://github.com/docker/swarmkit/pull/2519 [manager/dispatcher] Synchronize Dispatcher.Stop() with incoming rpcs.
vndr engine:
```
$ vndr github.com/docker/swarmkit
```
vndr cli:
```
$ cd components/cli
$ make -f docker.Makefile shell
$ vndr github.com/docker/swarmkit
```
comparison of upstream changes: …
=> [18.03] vndr swarmkit to 49a9d7f

components/engine/daemon/cluster/executor/container/adapter.go, components/engine/daemon/network.go, components/engine/integration/network/service_test.go
Cherry-pick of https://github.com/moby/moby/pull/36316 for 18.03, to address https://github.com/moby/moby/issues/36247 (a regression introduced in https://github.com/moby/moby/pull/36316)
```
git checkout -b 18.03-backport-selansen-36247 upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 7cf8b20762cc9491f52ff3f3d94c880378183696
```
No conflicts
With the inclusion of PR 30897, creating service for host network
fails in 18.02. Modified IsPreDefinedNetwork check and return
NetworkNameError instead of errdefs.Forbidden to address this issue
=> [18.03] Fix to address regression caused by PR 30897

components/cli/vendor.conf, components/engine/vendor.conf, components/engine/vendor/github.com/docker/swarmkit/manager/controlapi/service.go
This PR brings in https://github.com/docker/swarmkit/pull/2523; https://github.com/docker/swarmkit/compare/49a9d7f6ba3c1925262641e694c18eb43575f74b...11d7b06f48bc1d73fc6d8776c3552a4b11c94301
CLI vendoring is also updated, but did not bring in changes
=> [18.03] disallow attaching ingress network

components/packaging/deb/build-deb, components/packaging/rpm/centos-7/docker-ce.spec, components/packaging/rpm/fedora-26/docker-ce.spec, components/packaging/rpm/fedora-27/docker-ce.spec
```
git cherry-pick -x -s -Xsubtree="components/packaging" 59164bedeab571029805a107e8e5a32fc9cd56b3
```
Cherry pick of https://github.com/docker/docker-ce-packaging/pull/88
Cherry pick was __clean__
Binary installation was broken after the
hack/dockerfile/install-binaries script was removed.
This remedies that.
(cherry picked from commit 59164bedeab571029805a107e8e5a32fc9cd56b3)
=> [18.03] Fixes binary installation

components/engine/hack/dockerfile/install/containerd.installer, components/engine/hack/dockerfile/install/proxy.installer, components/engine/hack/dockerfile/install/runc.installer
backport of https://github.com/moby/moby/pull/36518 for 18.03
```
git checkout -b 18.03-fix_static_builds upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 63c7bb24637fdbfd905096ecc75b435ecefd31e9
git cherry-pick -s -S -x -Xsubtree=components/engine 5e4885b9afb1de30133627ce751af2c0e7b72a4e
```
no conflicts
ping @seemethere @andrewhsu @vdemeester PTAL
=> [18.03] fix static builds

components/packaging/deb/build-deb, components/packaging/rpm/centos-7/docker-ce.spec, components/packaging/rpm/fedora-26/docker-ce.spec, components/packaging/rpm/fedora-27/docker-ce.spec
backport of:
* https://github.com/docker/docker-ce-packaging/pull/90 Use new 'dynamic' args in install.sh
with cherry-pick of https://github.com/docker/docker-ce-packaging/pull/90/commits/130f741:
```
$ git cherry-pick -s -x -Xsubtree=packaging 130f741
```
no conflicts.
=> [18.03] Use new 'dynamic' args in install.sh

components/engine/integration-cli/docker_cli_events_unix_test.go, components/engine/integration-cli/docker_cli_run_unix_test.go
```
git cherry-pick -x -s -Xsubtree="components/engine" 620ddc78a1437feaa42f40853ef586d268991620
```
These tests were enabled by changing a config option on the ci
machines, instead of from a patch, so let me disable them
for now on ppc64le and open up another patch to enable them, where I can find
out what the issues are with them.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>
(cherry picked from commit 620ddc78a1437feaa42f40853ef586d268991620)
=> [18.03] skip ppc64le oom tests for now 

components/engine/daemon/network.go, components/engine/integration/network/service_test.go, components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/config/config.go, components/engine/vendor/github.com/docker/libnetwork/controller.go, components/engine/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go, components/engine/vendor/github.com/docker/libnetwork/drivers/ipvlan/ipvlan_endpoint.go, components/engine/vendor/github.com/docker/libnetwork/drivers/ipvlan/ipvlan_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers/macvlan/macvlan_endpoint.go, components/engine/vendor/github.com/docker/libnetwork/drivers/macvlan/macvlan_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go, components/engine/vendor/github.com/docker/libnetwork/drivers_ipam.go, components/engine/vendor/github.com/docker/libnetwork/ipams/builtin/builtin_unix.go, components/engine/vendor/github.com/docker/libnetwork/ipams/builtin/builtin_windows.go, components/engine/vendor/github.com/docker/libnetwork/ipamutils/utils.go, components/engine/vendor/github.com/docker/libnetwork/network.go, components/engine/vendor/github.com/docker/libnetwork/service_common.go, components/engine/vendor/github.com/docker/libnetwork/vendor.conf
Backport of https://github.com/moby/moby/pull/36538 / https://github.com/docker/libnetwork/pull/2101 for 18.03
```
git checkout -b 18.03-ingress-fix upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 805b6a7f749a6c7cbb237e21ee7260d536621808
git cherry-pick -s -S -x -Xsubtree=components/engine 3da4ebf355d3494d1403b2878a1ae6958b2724e9
git cherry-pick -s -S -x -Xsubtree=components/engine bebad150c9c3bc6eb63758c10ef24b9298ecf6e2
```
no conflicts
ping @ctelfer @fcrisciani @brawong @vdemeester PTAL
=> [18.03] Fix automatic removal of ingress sandbox when last service leaves

components/engine/daemon/oci_linux.go, components/engine/daemon/oci_linux_test.go
Backport of https://github.com/moby/moby/pull/36526 for 18.03 (fixes https://github.com/moby/moby/issues/36503)
```
git checkout -b 18.03-backport-ipc-ro upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine cad74056c09f6276b0f4a996a1511553177cd3d7
git cherry-pick -s -S -x -Xsubtree=components/engine 33dd562e3acff71ee18a2543d14fcbecf9bf0e62
```
no conflicts
=> [18.03] backport daemon/setMounts(): do not make /dev/shm ro

components/engine/hack/dockerfile/install/proxy.installer, components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/bitseq/sequence.go, components/engine/vendor/github.com/docker/libnetwork/ipam/allocator.go, components/engine/vendor/github.com/docker/libnetwork/vendor.conf, components/engine/vendor/golang.org/x/sync/README, components/engine/vendor/golang.org/x/sync/README.md
cherry-pick of https://github.com/moby/moby/pull/36589 for 18.03
```
git checkout -b 18.03-fix-duplicate-ip-issues upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 55e0fe24db68b16edccb2fa49c3b1b9d3a9ce58c
```
no conflicts
This updates libnetwork to 8892d7537c67232591f1f3af60587e3e77e61d41 to bring in
IPAM fixes for duplicate IP addresses.
- IPAM tests (libnetwork PR 2104) (no changes in vendored files)
- Fix for Duplicate IP issues  (libnetwork PR 2105)
Also bump golang/x/sync to match libnetwork (no code-changes, other
than the README being updated)
(cherry picked from commit 55e0fe24db68b16edccb2fa49c3b1b9d3a9ce58c)
Please do not send pull requests to this …
=> [18.03] Update libnetwork with fixes for duplicate IP addresses

components/engine/hack/dockerfile/install/proxy.installer, components/engine/vendor.conf, components/engine/vendor/github.com/docker/libnetwork/drivers/windows/windows.go
backport:
* https://github.com/moby/moby/pull/36603 Update libnetwork to fix stale HNS endpoints on Windows
with cherry-pick of https://github.com/moby/moby/pull/36603/commits/fb364f0:
```
$ git cherry-pick -s -x -Xsubtree=components/engine fb364f0
```
no conflicts.
=> [18.03] Update libnetwork to fix stale HNS endpoints on Windows

components/cli/cli/command/image/trust_test.go, components/cli/cli/trust/trust.go, components/cli/vendor.conf, components/cli/vendor/github.com/docker/docker/client/hijack.go, components/cli/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go, components/cli/vendor/github.com/docker/docker/registry/config.go, components/cli/vendor/github.com/docker/docker/vendor.conf
backport:
* https://github.com/docker/cli/pull/975 vendor: update moby to ed7b6428
with cherry-pick:
```
$ git cherry-pick -s -x -Xsubtree=components/cli a1cbaa8
```
no conflicts.
=> [18.04] vendor: update moby to ed7b6428

components/engine/libcontainerd/client_daemon.go, components/engine/plugin/executor/containerd/containerd.go, components/engine/plugin/executor/containerd/containerd_test.go
backport:
* https://github.com/moby/moby/pull/36715 Make sure plugin container is removed on failure
with cherry-pick of git commit https://github.com/moby/moby/pull/36715/commits/f81172b:
```
$ git cherry-pick -s -x -Xsubtree=components/engine f81172b
```
no conflicts
=> [18.04] Make sure plugin container is removed on failure

components/engine/cmd/dockerd/daemon.go, components/engine/daemon/cluster/cluster.go, components/engine/daemon/cluster/noderunner.go, components/engine/daemon/config/config.go
brings in:
* https://github.com/moby/moby/pull/36726 Expose swarmkit's Raft tuning parameters in engine config
with cherry-pick of git commit https://github.com/moby/moby/pull/36726/commits/275a1ca:
```
$ git cherry-pick -s -x -Xsubtree=components/engine 275a1ca
```
no conflicts
=> [18.04] Expose swarm raft tuning parameters in engine config

components/engine/integration-cli/fixtures/plugin/plugin.go, components/engine/integration/plugin/volumes/cmd/cmd_test.go, components/engine/integration/plugin/volumes/cmd/dummy/main.go, components/engine/integration/plugin/volumes/cmd/dummy/main_test.go, components/engine/integration/plugin/volumes/helpers_test.go, components/engine/integration/plugin/volumes/main_test.go, components/engine/integration/plugin/volumes/mounts_test.go, components/engine/plugin/v2/plugin_linux.go
Backport fixes from moby/moby#36711
```
git cherry-pick -x -s -Xsubtree=components/engine ec90839ca302ca53a7d55e4c7f79e7b4779f5e15
```
=> [18.04] Don't sort plugin mounts slice

components/engine/integration-cli/fixtures/plugin/plugin.go, components/engine/integration/plugin/volumes/cmd/cmd_test.go, components/engine/integration/plugin/volumes/cmd/dummy/main.go, components/engine/integration/plugin/volumes/cmd/dummy/main_test.go, components/engine/integration/plugin/volumes/helpers_test.go, components/engine/integration/plugin/volumes/main_test.go, components/engine/integration/plugin/volumes/mounts_test.go, components/engine/plugin/v2/plugin_linux.go
Backport fixes from moby/moby#36711
```
git cherry-pick -x -s -Xsubtree=components/engine ec90839ca302ca53a7d55e4c7f79e7b4779f5e15
```
=> [18.03] Don't sort plugin mounts slice

CHANGELOG.md
Removes a line talking about updating runc to a specific commit.
Runc was updated twice during separate rcs and this line might cause confusion for users in regards to what version of runc to expect in 18.03.
Signed-off-by: corbin-coleman <corbin.coleman@docker.com>
=> [18.03] Remove update runc line

components/engine/integration/system/cgroupdriver_systemd_test.go
Backport of https://github.com/moby/moby/pull/36172 for 18.03
```
git checkout -b 18.03-systemd-memlimit upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 4ca5c5361059e29ed31074ca5b96f8b2030b5f99
git push --set-upstream origin 18.03-systemd-memlimit
```
No conflicts
This is a test case for issue https://github.com/moby/moby/issues/35123,
making sure we can set container's memory limit when using
`native.cgroupdriver=systemd`.
[v2: skip if no systemd present]
[v3: add --iptables=false to avoid flaky tests with t.Parallel()]
[v4: rebase after PR#36507 merge]
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
(cherry picked from commit 4ca5c5361059e29ed31074ca5b96f8b2030b5f99)
Please do not send pull requests to this …
=> [18.03] Test for systemd cgroupdriver memory setting

components/engine/daemon/exec_linux.go, components/engine/daemon/exec_linux_test.go
cherry-pick of https://github.com/moby/moby/pull/36466
```
git checkout -b 18.03-fix-exec-apparmor upstream/18.03 
git cherry-pick -s -S -x -Xsubtree=components/engine 8f3308ae10ec9ad0dd4edfb46fde53a0e1e19b34
```
No conflicts
fixes https://github.com/moby/moby/issues/36456
Exec processes do not automatically inherit AppArmor profiles from the container.
This patch sets the AppArmor profile for the exec process.
Before this change:
```bash
apparmor_parser -q -r <<EOF
#include <tunables/global>
profile deny-write flags=(attach_disconnected) {
#include <abstractions/base>
file,
network,
deny /tmp/** w,
capability,
}
EOF
docker run -dit --security-opt "apparmor=deny-write" --name aa busybox
```
Running `docker exec` doesn't get the profile applied:
```bash
docker exec aa sh -c 'mkdir …
```
=> [18.03] Fix AppArmor not being applied to Exec processes

components/cli/cli/command/manifest/create_list.go, components/cli/docs/reference/commandline/manifest.md
backport of https://github.com/docker/cli/pull/978 for 18.03
```
git checkout -b 18.03-backport-fix-manifest-docs-typo upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/cli 9fa6bd4174a1bedfae8f705e694be477f64a45ce
git push -u origin 18.03-backport-fix-manifest-docs-typo
```
no conflicts
=> [18.03] [docs] Fix typo in manifest command docs: updated `MANFEST` to `MANIFEST`

components/engine/daemon/cluster/executor/container/executor.go
backport of https://github.com/moby/moby/pull/36769 for 18.03
```
git checkout -b 18.03-backport-defensive-attachment-processing upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 454128c6e82cded211c1412e3eb350b1f7533ee2
git push -u origin 18.03-backport-defensive-attachment-processing
```
no conflicts
We have seen a panic when re-joining a node to a swarm cluster. The
cause of the issue is unknown, so we just need to add a test for nil
objects and log when we get the condition. Hopefully this can prevent
the crash and we can recover the config at a later time.
Signed-off-by: Stephen J Day <stephen.day@docker.com>
(cherry picked from commit 454128c6e82cded211c1412e3eb350b1f7533ee2)
Please do not send pull requests to …
=> [18.03] daemon/cluster: handle partial attachment entries during configure

components/cli/contrib/completion/bash/docker, components/cli/docs/extend/index.md, components/cli/docs/reference/commandline/build.md, components/cli/docs/reference/commandline/history.md, components/cli/docs/reference/commandline/load.md, components/cli/docs/reference/commandline/run.md, components/cli/docs/reference/commandline/secret_create.md, components/cli/docs/reference/run.md
docs and completion cherry-picks for 18.03 of:
- https://github.com/docker/cli/pull/957 Docs touch-ups for "autoremove" and broken anchor
- https://github.com/docker/cli/pull/962 Clarify behaviour of restart policy in run ref doc
- https://github.com/docker/cli/pull/970 Clarify --build-arg documentation
- https://github.com/docker/cli/pull/979 Use printf, not echo when creating secrets
- https://github.com/docker/cli/pull/980 Fix --format example for docker history
- https://github.com/docker/cli/pull/988 Update examples to reflect docker-runc's runtime root for plugins.
- https://github.com/docker/cli/pull/999 build.md: Document --build-arg without value
- https://github.com/docker/cli/pull/1007 docs: Typofix in example "docker image ls"
- https://github.com/docker/cli/pull/1004 Add bash …
=> [18.03] backport docs and completion fixes

components/cli/cli/command/system/version.go
Use tabwriter to print the version output
backport of https://github.com/docker/cli/pull/965 for 18.03
```
git checkout -b 18.03-backport-fix-version-output upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/cli 48eb7a082dfcca6b16a3466a98cd27b04deb07c7
git push -u origin 18.03-backport-fix-version-output
```
no conflicts
=> [18.03] Fix docker version output alignment

components/engine/container/archive.go, components/engine/container/container.go, components/engine/daemon/export.go, components/engine/daemon/oci_linux.go, components/engine/daemon/oci_windows.go, components/engine/integration/container/export_test.go
Cherry-picks for 18.03 of
- https://github.com/moby/moby/pull/36586 ExportContainer: do not panic
- https://github.com/moby/moby/pull/36606 integration/TestExportContainerAfterDaemonRestart: add
- https://github.com/moby/moby/pull/36610 Windows: Hyper-V containers are broken after 36586 was merged
fixes https://github.com/moby/moby/issues/36561
fixes https://github.com/docker/for-mac/issues/2679
no conflicts
=> [18.03] ExportContainer: do not panic

components/engine/plugin/manager_linux.go, components/engine/plugin/manager_linux_test.go
cherry-pick of https://github.com/moby/moby/pull/36646 for 18.03.
```
git checkout -b 18.03-err_return upstream/18.03 
git cherry-pick -s -S -x -Xsubtree=components/engine 89a882e2f1706e567a8514209701892b40da7a62 
```
no conflicts
=> [18.03] Add missing error return for plugin creation.

components/cli/cli/command/stack/swarm/deploy_composefile.go, components/cli/cli/command/stack/swarm/deploy_test.go
backport of https://github.com/docker/cli/pull/963 for 18.03
```
git checkout -b 18.03-backport-fix-stack-deploy-after-force upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/cli 76439457d2607806d07b1627fd0e25736ce14fae
git push -u origin 18.03-backport-fix-stack-deploy-after-force
```
no conflicts
When updating a service with the `--force` option, the `ForceUpdate`
property of the taskspec is incremented.
Stack deploy did not take this into account, and reset this
field to its default value (0), causing the service to be
re-deployed.
This patch copies the existing value before updating the service.
=> [18.03] Fix stack deploy re-deploying service after --force

components/engine/distribution/push_v2.go, components/engine/distribution/push_v2_test.go
backport of https://github.com/moby/moby/pull/36509 for 18.03. Fixes https://github.com/moby/moby/issues/36309
```
git checkout -b 18.03-distribution-cache upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 8b387b165ab2eaab3f9fdac25caa186d05d236a0
git push -u origin 18.03-distribution-cache
```
(no conflicts)
local digest cache will be removed when error occured on push image
but it should not be removed if it is an auth error while on auth was
provided
=> [18.03] fix(distribution): digest cache should not be moved if it was an auth error

components/engine/daemon/cluster/noderunner.go
backport of https://github.com/moby/moby/pull/36672 for 18.03
```
git checkout -b 18.03-backport-election upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 6abee2008b314a65553202b15d9a333d171e3433
git push -u origin 18.03-backport-election
```
cherry-pick wasn't clean due to https://github.com/moby/moby/pull/36240 not being in 18.03, but trivial to resolve
```patch
diff --cc components/engine/daemon/cluster/noderunner.go
index f832aca145,989551a6ca..0000000000
--- a/components/engine/daemon/cluster/noderunner.go
+++ b/components/engine/daemon/cluster/noderunner.go
@@@ -120,12 -120,18 +120,27 @@@ func (n *nodeRunner) start(conf nodeSta
JoinAddr:           joinAddr,
StateDir:           n.cluster.root,
JoinToken:          conf.joinToken,
++<<<<<<< HEAD
+ …
```
=> [18.03] Increase raft ElectionTick to 10xHeartbeatTick

components/engine/integration/plugin/authz/authz_plugin_test.go, components/engine/pkg/authorization/response.go
When the authz response buffer limit is hit, perform a flush.
This prevents excessive buffer sizes, especially on large responses
(e.g. /containers/<id>/archive or /containers/<id>/export).
Backports moby/moby#36595 @ 74f8e47352e71aad4015d8d9dea8f16e7a055863
Which is a fix for https://github.com/moby/moby/issues/36576
```
git cherry-pick -x -s -Xsubtree=components/engine 74f8e47352e71aad4015d8d9dea8f16e7a055863
```
=> [18.03] backport authz buffer fix

components/engine/libcontainerd/client_daemon.go, components/engine/plugin/executor/containerd/containerd.go, components/engine/plugin/executor/containerd/containerd_test.go
backport of https://github.com/moby/moby/pull/36715 for 18.03
```
git checkout -b 18.03-backport-plugin_exec_fixes upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine f81172b9031160218e51fb2a7dbeee19962a60a9
git push -u origin 18.03-backport-plugin_exec_fixes
```
=> [18.03] Make sure plugin container is removed on failure

CHANGELOG.md
- Remove low-level code changes from changelog
- Remove features/fixes that were backported to 18.06, so already shipped
- Re-organised some change to be in a more suitable section
- Add information about deprecated features, and distros
I can to the list of change by;
- First looking at all changes between 18.06.0-rc1 and 18.09.0-tp1 https://github.com/docker/engine/compare/v18.06.0-ce-rc1...v18.09.0-ce-tp0 (both those tags are ~ the point at which their release branches were cut)
- Then looking at all changes that were added in the release branch itself https://github.com/docker/engine/compare/v18.09.0-ce-tp0...v18.09.0-beta5
Same was done for the CLI:
- https://github.com/docker/cli/compare/v18.06.0-ce-rc1...v18.09.0-ce-tp0
- https://github.com/docker/cli/compare/v18.09.0-ce-tp0...v18.0 …
=> [18.09] update change-log

CHANGELOG.md
Originally reported here: https://github.com/docker/for-linux/issues/610
=> [18.09 Fix link to release notes to be an actual link

components.conf
Since it was decided that github.com/moby/moby houses the release branches
of docker engine, maintaining two repos with release branches makes it
error-prone to manage, allowing for backports to slip by and git histories
to be inconsistent.
After this is merged and cherry-picked to other release branches on docker-ce
the plan is to archive the docker/engine repository.
=> components: use moby/moby instead of docker/engine

LICENSE
This repository was missing a license, but since it's been created mostly from bits of `github.com/docker/docker`, I figured that license was probably appropriate for this top-level (since the individual vendored directories should have their `LICENSE` files intact anyhow).
A quick `diff` to show that it's 100% identical:
```console
$ diff -u \
<(curl -fsSL 'https://github.com/docker/docker/raw/master/LICENSE') \
<(curl -fsSL 'https://github.com/tianon/docker-ce/raw/license/LICENSE')
$ 
```
=> Add LICENSE (copy of docker/docker's Apache-2.0 file)

components.conf
Since it was decided that github.com/moby/moby houses the release branches
of docker engine, maintaining two repos with release branches makes it
error-prone to manage, allowing for backports to slip by and git histories
to be inconsistent.
After this is merged and cherry-picked to other release branches on docker-ce
the plan is to archive the docker/engine repository.
(cherry picked from commit 24188c2)
Cherry-pick of https://github.com/docker/docker-ce/pull/641
=> [19.03] components: use moby/moby instead of docker/engine

README.md
The page was not linked from README and was not easily reachable.
=> README.md: add link to CONTRIBUTING.md#submitting-pull-requests

README.md
The previous wording was causing confusion to some people.
=> Clarify that Docker CE repo is deprecated, but Docker CE itself is NOT deprecated
