- components/engine/hack/make/.integration-daemon-start
- components/engine/hack/make/.integration-test-helpers
- components/engine/integration-cli/docker_cli_config_test.go
(cherry picked from commit 0b90edc22fa95e04b4d3208a72bb276be699b260)
---
Cherry pick of moby/moby#33474
> Use actual cli version for TestConfigHTTPHeader

- components/engine/daemon/start_windows.go
Signed-off-by: Sandeep Bansal <sabansal@microsoft.com>
(cherry picked from commit b8e8dcd6e031d005a2d46d95f84da35b436cd870)
--- 
Cherry pick of moby/moby#33311
> Adding support for DNS search on RS1

- components/engine/api/swagger.yaml
- components/engine/api/types/swarm/task.go
- components/engine/daemon/cluster/convert/service.go
Signed-off-by: Evan Hazlett <ejhazlett@gmail.com>
(cherry picked from commit 8eeba751983d6499a07fcd21c26f381eb1d17d19)
---
Cherry pick from moby/moby#33308
> remove RuntimeData from cluster and types

- components/cli/cli/command/stack/client_test.go
- components/cli/cli/command/stack/common.go
- components/cli/cli/command/stack/remove.go
- components/cli/cli/command/stack/remove_test.go
Signed-off-by: John Stephens <johnstep@docker.com>
(cherry picked from commit f05cd11ee234804d85b3aadae0777610809530a4)
---
Cherry pick of docker/cli#134
> Remove stack configs on stack removal

- components/cli/cli/compose/convert/service.go
Signed-off-by: John Stephens <johnstep@docker.com>
(cherry picked from commit b7cac96f69d10436d740365157f72bf08a2a456f)
---
Cherry pick of docker/cli#135
> Include stack service configs in service specs

- components/cli/cli/compose/loader/loader.go
For stack compose files, use filepath.IsAbs instead of path.IsAbs, for
bind-mounted service volumes, because filepath.IsAbs handles Windows
paths, while path.IsAbs does not.
Signed-off-by: John Stephens <johnstep@docker.com>
(cherry picked from commit 9043d39deaa9b8d6b64efd5b4eb0a2225d91dee2)
---
Cherry pick of docker/cli#136
> Fix stack compose bind-mount volumes for Windows

- components/cli/.gitignore
- components/cli/Makefile
- components/cli/docker.Makefile
- components/cli/scripts/docs/generate-man.sh
- components/cli/scripts/docs/generate-yaml.sh
Follow up to https://github.com/docker/docker-ce/pull/23
~Will rebase once #23 merged.~
The commit to review is f148100. It's a cherry-pick of https://github.com/docker/cli/pull/154
> Add scripts and targets for manpages and yamldocs

- components/cli/cli/command/stack/deploy_composefile.go
- components/cli/cli/command/stack/deploy_composefile_test.go
- components/cli/cli/compose/convert/service.go
- components/cli/cli/internal/test/network/client.go
- components/cli/scripts/test/watch
Cherry-picking from https://github.com/docker/cli/pull/132
> Host and Bridge network support in docker stack deploy

- components/cli/vendor.conf
- components/cli/vendor/github.com/docker/docker/pkg/term/termios_bsd.go
- components/engine/pkg/term/termios_bsd.go
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
(cherry picked from commit 17ec46a24316f59c808c112e3ca46d7c442a785a)
---
Cherry pick of moby/moby#33502
**NOTES:**
- This manually vendors `github.com/docker/docker` to get the associated changes in `github.com/docker/docker/pkg/term/termios_bsd.go`
> Set OPOST on bsd

- components/cli/scripts/docs/generate-man.sh
Related to https://github.com/docker/cli/pull/158
> [cli] fix manpages script

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/libnetwork/controller.go
- components/engine/vendor/github.com/docker/libnetwork/network.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/cluster.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/delegate.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/event_delegate.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdb.go
This is a 17.06 equivalent cherry-pick of
https://github.com/moby/moby/pull/33463
Signed-off-by: Madhu Venugopal <madhu@docker.com>
> Vendoring libnetwork b54433f6459b84eae77892d0d359c1bafb133529

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/ca/config.go
- components/engine/vendor/github.com/docker/swarmkit/ca/external.go
- components/engine/vendor/github.com/docker/swarmkit/manager/manager.go
- components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/raft.go
Related to docker/for-linux#2
/cc @mavenugo @andrewhsu @aaronlehmann 
Includes:
- docker/swarmkit#2203
- docker/swarmkit#2210
- docker/swarmkit#2212
> [17.06] Re-vendor SwarmKit to 4b872cfac8ffc0cc7fff434902cc05dbc7612da5

- components/packaging/deb/Makefile
- components/packaging/deb/common/rules
- components/packaging/deb/debian-jessie/Dockerfile.armv7l
- components/packaging/deb/debian-jessie/Dockerfile.x86_64
- components/packaging/deb/debian-stretch/Dockerfile.armv7l
- components/packaging/deb/debian-stretch/Dockerfile.x86_64
- components/packaging/deb/debian-wheezy/Dockerfile.armv7l
- components/packaging/deb/debian-wheezy/Dockerfile.x86_64
- components/packaging/deb/ubuntu-trusty/Dockerfile.armv7l
- components/packaging/deb/ubuntu-trusty/Dockerfile.x86_64
- components/packaging/deb/ubuntu-xenial/Dockerfile.armv7l
- components/packaging/deb/ubuntu-xenial/Dockerfile.x86_64
- components/packaging/deb/ubuntu-yakkety/Dockerfile.armv7l
- components/packaging/deb/ubuntu-yakkety/Dockerfile.x86_64
- components/packaging/deb/ubuntu-zesty/Dockerfile.armv7l
- components/packaging/deb/ubuntu-zesty/Dockerfile.x86_64
- components/packaging/rpm/Makefile
- components/packaging/rpm/centos-7/Dockerfile.x86_64
- components/packaging/rpm/centos-7/docker-ce.spec
- components/packaging/rpm/fedora-24/Dockerfile.x86_64
- components/packaging/rpm/fedora-24/docker-ce.spec
- components/packaging/rpm/fedora-25/Dockerfile.x86_64
- components/packaging/rpm/fedora-25/docker-ce.spec
Cherry-picked from PR docker/docker-ce-packaging#12
(cherry picked from commit e14fca86f8230e10d79a7bfae2873a98a16bb44d)
> generate man pages

- components/packaging/deb/Makefile
- components/packaging/deb/ubuntu-xenial/Dockerfile.s390x
- components/packaging/deb/ubuntu-yakkety/Dockerfile.s390x
- components/packaging/deb/ubuntu-zesty/Dockerfile.s390x
- components/packaging/rpm/Makefile
- components/packaging/static/Makefile
- components/packaging/static/hash_files
Cherry-pick a few choice commits for getting s390x man pages built and hash files for static binaries:
* docker/docker-ce-packaging#15
* docker/docker-ce-packaging#14
* docker/docker-ce-packaging#2
* docker/docker-ce-packaging#1
> update with latest changes from docker-ce-packaging

- CHANGELOG.md
> Update 17.06 CHANGELOG with rc2 changes

- components/engine/daemon/health.go
- components/engine/integration-cli/docker_cli_health_test.go
Cherry-picked from: moby/moby#33249
The health check process doesn't have all the environment
varialbes in the container or has them set incorrectly.
This patch should fix that problem.
Signed-off-by: Boaz Shuster <ripcurld.github@gmail.com>
(cherry picked from commit 5836d86ac4d617e837d94010aa60384648ab59ea)
> Add container environment variables correctly to the health check

- components/engine/builder/dockerfile/evaluator.go
- components/engine/integration-cli/docker_api_attach_test.go
- components/engine/integration-cli/docker_api_build_test.go
- components/engine/integration-cli/request/request.go
Cherry-picked from: moby/moby#33524
Signed-off-by: Daniel Nephin <dnephin@docker.com>
(cherry picked from commit f1ade82d82e6436971c6b7d08eb1da57ed9ba756)
> Fix Cache with ONBUILD

- components/engine/api/server/middleware/debug.go
Cherry-picked from: moby/moby#33464
Signed-off-by: Ying Li <ying.li@docker.com>
(cherry picked from commit d60f18204978d438d1eb336512576d47991c8ac1)
> Do not log the CA config CA signing key in debug mode.

- components/engine/integration-cli/docker_cli_swarm_test.go
Cherry-picked from: moby/moby#33307
Signed-off-by: Dong Chen <dongluo.chen@docker.com>
(cherry picked from commit 59b2d0473af5155bb31adcc17bc36857ebd13a15)
> Event tests need to wait for events

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/ca/reconciler.go
- components/engine/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go
- components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go
This includes the following P0+P1 changes from swarmkit:
cc @aaronlehmann
> [17.06] Re-vendor swarmkit

- CHANGELOG.md
> Remove unneeded line in 17.06 CHANGELOG

- components/cli/dockerfiles/Dockerfile.cross
- components/cli/dockerfiles/Dockerfile.dev
- components/cli/dockerfiles/Dockerfile.lint
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
(cherry picked from commit b38c49411b68884d2424aca311ea1ccff237b270)
Cherry-pick of https://github.com/docker/cli/pull/173
> Update golang 1.8.3

- components/engine/CHANGELOG.md
Cherry-picked from: moby/moby#33606
> Backport 17.05.0-ce changelog to master

- components/engine/builder/remotecontext/detect.go
Cherry-picked from: moby/moby#33363
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
(cherry picked from commit 23628bd7efb0aae565cea5ee040e373b0c93fd8d)
> Fix cancelling builder on chunked requests

- components/engine/daemon/logger/adapter.go
- components/engine/daemon/logger/plugin.go
Cherry-picked from: moby/moby#33583
Signed-off-by: Peter Bücker <peter.buecker@gmail.com>
(cherry picked from commit e908e1a357b435d7fab497d51cdd3e58458a0590)
> Logging driver should receive same file in start/stop request

- components/engine/docs/deprecated.md
Cherry-picked from: moby/moby#33473
Related to PR #64 
(cherry picked from commit 43239f62bedc4721d27744d21c122622988bb3ae)
> Update deprecated.md for removal of --email flag

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/libnetwork/agent.go
- components/engine/vendor/github.com/docker/libnetwork/agent.proto
- components/engine/vendor/github.com/docker/libnetwork/common/setmatrix.go
- components/engine/vendor/github.com/docker/libnetwork/endpoint.go
- components/engine/vendor/github.com/docker/libnetwork/network.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdb.go
- components/engine/vendor/github.com/docker/libnetwork/sandbox.go
- components/engine/vendor/github.com/docker/libnetwork/service.go
- components/engine/vendor/github.com/docker/libnetwork/service_common.go
- components/engine/vendor/github.com/docker/libnetwork/service_linux.go
This is a cherry-pick of https://github.com/moby/moby/pull/33634
that brings in https://github.com/docker/libnetwork/pull/1796.
Signed-off-by: Madhu Venugopal <madhu@docker.com>
> Vendoring libnetwork 4f5310be349d9299f6cab6d5822312f00cfa965c

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/manager/allocator/networkallocator/networkallocator.go
- components/engine/vendor/github.com/docker/swarmkit/manager/manager.go
Includes https://github.com/docker/swarmkit/pull/2244 ("Fixing error with host network mode on upgrade from pre 17.06 versions")
> Vendor swarmkit bf9b892

- components/packaging/rpm/centos-7/docker-ce.spec
- components/packaging/rpm/fedora-24/docker-ce.spec
- components/packaging/rpm/fedora-25/docker-ce.spec
to fix rpmbuild error:
```
01:32:15 error: no description in %changelog
```
(cherry picked from commit 659d6015b6bf8ec3c24cf5377f3eda88beed0a10)
> cherry-pick update rpm changelog

- components/engine/daemon/cluster/convert/swarm.go
- components/engine/integration-cli/docker_api_swarm_test.go
- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/ca/certificates.go
- components/engine/vendor/github.com/docker/swarmkit/manager/controlapi/cluster.go
- components/engine/vendor/github.com/docker/swarmkit/manager/scheduler/nodeset.go
- components/engine/vendor/github.com/docker/swarmkit/manager/scheduler/scheduler.go
Related to docker/for-linux#37
Related PRs:
- vendoring swarmkit's `bump_v17.06.0` branch: 
- docker/swarmkit#2268
- docker/swarmkit#2224
- docker/swarmkit#2263
- cherry-pick:
- moby/moby#33712: `git cherry-pick -x -s -Xsubtree=components/engine bdfbd22afbbf16a07f0316656c6c17453df3e0f7`
> Fix swarmkit issues for 17.06.0-rc5

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/libnetwork/agent.go
- components/engine/vendor/github.com/docker/libnetwork/common/setmatrix.go
- components/engine/vendor/github.com/docker/libnetwork/network.go
- components/engine/vendor/github.com/docker/libnetwork/service.go
- components/engine/vendor/github.com/docker/libnetwork/service_common.go
- components/engine/vendor/github.com/docker/libnetwork/service_linux.go
Related to docker/for-linux#37
Brings in this pull request:
- https://github.com/docker/libnetwork/pull/1808
> [engine] Vendor libnetwork to 20bf4e23da1bb3f9d3dc70e4cf531b84c45947bd

- CHANGELOG.md
---
/cc @mavenugo for the changelog entries for libnetwork cherry-picking (#55)
> Update changelog for 17.06.0-ce RC5

- components/packaging/deb/common/control
- components/packaging/rpm/centos-7/docker-ce.spec
- components/packaging/rpm/fedora-24/docker-ce.spec
- components/packaging/rpm/fedora-25/docker-ce.spec
Bringing in these PRs:
* docker/docker-ce-packaging#17
* docker/docker-ce-packaging#18
* docker/docker-ce-packaging#20
* docker/docker-ce-packaging#21
* docker/docker-ce-packaging#23
* docker/docker-ce-packaging#24
> cherry-pick packaging PRs for 17.06.0 RC5

- CHANGELOG.md
Built the changelog from the milestone page: https://github.com/docker/docker-ce/milestone/2?closed=1
> update changelog for docker-ce 17.06.1 rc1

- components/packaging/deb/ubuntu-xenial/Dockerfile.aarch64
- components/packaging/detect_alpine_image
```shell
git cherry-pick -x -s -Xsubtree="components/packaging" "94cbc76"
```
(cherry picked from commit 94cbc76b701b8b108f6a337b1695bd664f441bdc)
> [17.07] Add ubuntu-xenial aarch64 Dockerfile

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/manager/manager.go
Apologies, in https://github.com/docker/docker-ce/pull/136, I forgot about also including the following fix:
- https://github.com/docker/swarmkit/pull/2323 (run watchapi server on all managers)
> [17.07] Re-vendor swarmkit

- CHANGELOG.md
ping @andrewhsu anything to add packaging wise ?
ping @thaJeztah
> [17.07.x] Changelog

- components/engine/container/container.go
Signed-off-by: Abhinandan Prativadi <abhi@docker.com>
(cherry picked from commit bcb55c62024419a2f8fa7679e1e068cc43425636)
Signed-off-by: Abhinandan Prativadi <abhi@docker.com>
> [17.06] Fixing issue with driver opt not passed to drivers

- components/cli/contrib/completion/bash/docker
- components/cli/contrib/completion/zsh/_docker
Bash completion fixes:
* https://github.com/docker/cli/pull/254 https://github.com/docker/cli/commit/36b572dfdf6bc7b2519f494afe93130e3a8718b5
* https://github.com/docker/cli/pull/279 https://github.com/docker/cli/commit/1f8720717d58597cb4474e70fa6d534db132229b
* https://github.com/docker/cli/pull/280 https://github.com/docker/cli/commit/1d21a3dd7c4ffff80c093c005b910a131e7fc05a
* https://github.com/docker/cli/pull/281 https://github.com/docker/cli/commit/2caf425f02363a5894b5790dcde47a11808d23e1
* https://github.com/docker/cli/pull/283 https://github.com/docker/cli/commit/c40952b3058db3c6e44bca8c518d888b83878ce5 https://github.com/docker/cli/commit/211bd55ae736705a48908833a5e10491f613e255 https://github.com/docker/cli/commit/d585e554d5e3a16f424cb3d92d0f7be342b8c7ca
* …
> [17.06] Completion cherry picks

- CHANGELOG.md
> [17.06] Changelog

- CHANGELOG.md
Signed-off-by: Trapier Marshall <trapier.marshall@docker.com>
> [17.06] Docker user iptables changelog addition

- CHANGELOG.md
CC @vieux @andrewhsu @thaJeztah @tiborvass
> [17.06.1] Update changelog for 17.06.1-ce-rc3

- components/engine/daemon/build.go
Original PR message:
releaseableLayer includes automatic handling for creating a read/write layer and mounting it on a call to Mount(), but then does not correspondingly unmount the layer before trying to delete it, which will fail for some graphdrivers. Commit on a releaseable layer also leaks the tarstream for the layer. To fix this, the stream close is deferred in Commit and releaseRWLayer now correctly handles unmounting the layer before trying to delete it.  In addition, the changes include better error handling in Release() to make sure that errors are returned to the caller for failures on read/write layers instead of being ignored.# Please enter the commit message for your changes. Lines starting
Cherry-Pick note:
This version of the change was edited to merge with docker-ce …
> [17.06] Fixing releaseableLayer handling of layer streams and mounts.

- components/engine/daemon/cluster/tasks.go
Cherry-picked from https://github.com/moby/moby/pull/34235/commits/bd4f66c8f1f6ad4a2f228a957f293bc157e13d9c (https://github.com/moby/moby/pull/34235)
no conflicts
ping @aaronlehmann  @fcrisciani @tonistiigi
GetTasks can call GetService and GetNode with the read lock held. These
methods try to aquire the read side of the same lock. According to the
sync package documentation, this is not safe:
> If a goroutine holds a RWMutex for reading, it must not expect this or
> any other goroutine to be able to also take the read lock until the
> first read lock is released. In particular, this prohibits recursive
> read locking. This is to ensure that the lock eventually becomes
> available; a blocked Lock call excludes new readers from acquiring the
> lock.
Fix GetTasks to use the lower-level …
> [17.07] cluster: Avoid recursive RLock

- components/engine/api/swagger.yaml
- components/engine/api/types/swarm/common.go
- components/engine/docs/api/version-history.md
cherry-picks of:
- https://github.com/moby/moby/commit/c8dad44c326d9d2131f94babbc535e7f442db290 (https://github.com/moby/moby/pull/34202)
- https://github.com/moby/moby/commit/fc48b5529dca3907ade273921a14906be796e333 (https://github.com/moby/moby/pull/34247)
> [17.07] backport plugable secret api docs

- components/cli/cli/command/stack/deploy_composefile.go
- components/cli/cli/command/stack/deploy_composefile_test.go
Cherry-picked from https://github.com/docker/cli/pull/362/commits/7f53c99dfe5241a985dd5ce4bed6c116a2908b41 (https://github.com/docker/cli/pull/362), no conflicts
ping @alexmavr @dhiltgen PTAL
> [17.07] backport Skip inspect of built-in networks on stack deploy

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/libnetwork/agent.go
- components/engine/vendor/github.com/docker/libnetwork/common/caller.go
- components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/joinleave.go
- components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go
- components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_serf.go
- components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/overlay.go
- components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go
- components/engine/vendor/github.com/docker/libnetwork/endpoint_info.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdb.go
Update vendor of libnetwork to latest on bump_17.06 branch. Comparing changes: docker
https://github.com/docker/libnetwork/compare/0605cbc...2102668
```
$ vndr github.com/docker/libnetwork
```
> [17.06] vndr libnetwork to latest bump_17.06

- CHANGELOG.md
> [17.06] update changelog for docker-ce 17.06.1

- components/engine/daemon/graphdriver/aufs/aufs.go
- components/engine/daemon/graphdriver/aufs/aufs_test.go
backport fix:
* moby/moby#34587 Fix error removing diff path
with cherry-pick of https://github.com/moby/moby/pull/34587/commits/276b44608b04f08bdf46ce7c816b1f744bf24b7d
```
$ git cherry-pick -s -x -Xsubtree=components/engine 276b446
```
no conflicts
> [17.07] backport fix for removing diff path

- CHANGELOG.md
> [17.07] update changelog for latest 17.07 fix

- CHANGELOG.md
> [17.06] update changelog for 17.06.2-ce-rc1 release

- CHANGELOG.md
> [17.07] update changelog for 17.07.0

- CHANGELOG.md
Update changelog to represent all of the changes: https://github.com/docker/docker-ce/milestone/4?closed=1
> [17.06] update changelog for 17.06.2-ce

- .gitignore
- Makefile
This allows easier updating of Docker CE components
> Add update-components target, Fix PHONY Targets

- components/engine/integration-cli/docker_cli_run_unix_test.go
- components/engine/integration-cli/docker_cli_update_unix_test.go
Fix 2 tests:
* DockerSuite.TestRunWithNanoCPUs
* DockerSuite.TestUpdateWithNanoCPUs
backport:
* moby/moby/pull/34707 force inspect test format
with cherry pick moby/moby@8e6567cb837e1c885de5146517557c7a5d8a5f17
```
$ git cherry-pick -xs 8e6567cb837e1c885de5146517557c7a5d8a5f17
```
cherry-pick was clean, no conflict
> [17.09] backport: force inspect test format

- CHANGELOG.md
This is WIP and automatically generated.
Before I continue the manual triage tomorrow, I'd like to make sure we have all the commits needed.
> [17.09] add 17.09 changelog

- CHANGELOG.md
> [17.09] update changelog for 17.09.0-ce-rc2

- components/engine/daemon/disk_usage.go
back port of https://github.com/moby/moby/pull/34826 for 17.09
> [17.09] Fix variable shadowing causing LayersSize to be reported as 0

- CHANGELOG.md
> [17.09] update changelog for 17.09.0-ce-rc3

- CHANGELOG.md
From PRs merged in the `17.09.0` milestone: https://github.com/docker/docker-ce/milestone/6?closed=1
> [17.09] update changelog for 17.09.0-ce release

- CHANGELOG.md
> [17.10] update changelog for 17.10.0-ce-rc2

- CHANGELOG.md
> minimize changelog template

- CHANGELOG.md
> [17.10] update changelog for 17.10.0-ce

- CHANGELOG.md
> [17.11] update changelog for 17.11.0-ce-rc1

- CHANGELOG.md
> [17.11] Update changelog for 17.11.0 rc2

- CHANGELOG.md
> [17.11] add changelog for 17.11

- components/engine/container/health.go
backport fix:
* moby/moby#35482 container: protect health monitor channel
with cherry-pick of git commit https://github.com/moby/moby/pull/35482/commits/5b55747a523671fa6e626848060460a48d058451
```
$ git cherry-pick -s -x -Xsubtree=components/engine 5b55747
```
cherry-pick went in clean
> [17.11] container: protect health monitor channel

- CHANGELOG.md
> [17.11] update changelog for 17.11.0-ce-rc4

- CHANGELOG.md
> [17.11] Update changelog for 17.11.0-ce

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/connectionbroker/broker.go
- components/engine/vendor/github.com/docker/swarmkit/manager/controlapi/cluster.go
- components/engine/vendor/github.com/docker/swarmkit/manager/controlapi/node.go
- components/engine/vendor/github.com/docker/swarmkit/manager/manager.go
- components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/global/global.go
- components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/replicated/services.go
- components/engine/vendor/github.com/docker/swarmkit/manager/scheduler/filter.go
- components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/raft.go
- components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/transport/peer.go
- components/engine/vendor/github.com/docker/swarmkit/manager/state/raft/transport/transport.go
comparison of changes: https://github.com/docker/swarmkit/compare/dcd1f2d...b40ffde
brings in these changes from upstream:
* https://github.com/docker/swarmkit/pull/2404 [17.09] Increase gRPC request timeout to 20 seconds when sending snapshots #2404
* https://github.com/docker/swarmkit/pull/2442 [17.09] Don't filter nodes if logdriver==none or logdriver=="" #2442
* https://github.com/docker/swarmkit/pull/2454  [17.09] Error on cluster spec name change #2454
* https://github.com/docker/swarmkit/pull/2456 [17.09] Delete node attachments when node is removed #2456
* https://github.com/docker/swarmkit/pull/2457 [17.09] Provide custom gRPC dialer to override default proxy dialer (#2419) #2457
> [17.09] update swarmkit to b40ffde

- components/engine/container/health.go
backport of https://github.com/moby/moby/pull/35482 for 17.09
(cherry picked from commit 5b55747a523671fa6e626848060460a48d058451)
While this code was likely called from a single thread before, we have
now seen panics, indicating that it could be called in parallel. This
change adds a mutex to protect opening and closing of the channel. There
may be another root cause associated with this panic, such as something
that led to the calling of this in parallel, as this code is old and we
had seen this condition until recently.
This fix is by no means a permanent fix. Typically, bugs like this
indicate misplaced channel ownership. In idiomatic uses, the channel
should have a particular "owner" that coordinates sending and closure.
In this case, the owner of the channel is unclear, so it gets …
> [17.09] container: protect health monitor channel

- components/engine/builder/dockerfile/evaluator.go
- components/engine/integration-cli/docker_cli_build_test.go
fixes moby/moby/issues/33753
@dnephin 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> [17.09] builder: fix config leakage on shared parent stage

- CHANGELOG.md
> [17.09] update changelog for 17.09.1-ce-rc1

- CHANGELOG.md
Change the base branch to 17.12 once it's created.
ping @fcrisciani @tonistiigi @dnephin @thaJeztah @andrewhsu
> [17.12] add changelog for 17.12.0-ce-rc1

- CHANGELOG.md
> [17.09] update changelog for 17.09.1-ce

- CHANGELOG.md
> [17.12] update changelog for 17.12.0 rc2

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/libnetwork/diagnose/server.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/delegate.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/event_delegate.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/networkdbdiagnose.go
- components/engine/vendor/github.com/docker/libnetwork/networkdb/nodemgmt.go
Includes fixes for: 
- https://github.com/docker/libnetwork/pull/2036 Clean up node management logic
Vendored with: 
```
vndr github.com/docker/libnetwork 
```
Full diff: https://github.com/docker/libnetwork/compare/9bca9a4a220b158cc94402e0f8c2c7714eb6f503...7dd202d11b2078c063fefc614c9fb9e4615da0e1
> [17.12] backport network partition to 7dd202d11b2078c063fefc614c9fb9e4615da0e1

- CHANGELOG.md
Please see https://github.com/docker/docker.github.io/pull/5499
> [17.12] Fix CHANGELOG: rm entry mentioning a test fix

- components/engine/vendor.conf
- components/engine/vendor/github.com/docker/swarmkit/manager/allocator/cnmallocator/networkallocator.go
- components/engine/vendor/github.com/docker/swarmkit/manager/orchestrator/taskreaper/task_reaper.go
Contains fixes:
* https://github.com/docker/swarmkit/pull/2474
* https://github.com/docker/swarmkit/pull/2477
Comparison:
https://github.com/docker/swarmkit/compare/4429c763170d9ca96929249353c3270c19e7d39e...7598f7a937de4ad0a856012bd548009ceeb0d10e
> [17.12] bump swarmkit to 7598f7a

- CHANGELOG.md
> [17.12] update changelog for 17.12.0-ce-rc4

- CHANGELOG.md
Removing change that didn't make it in to the release.
> [17.12] Update changelog

- CHANGELOG.md
Ping @andrewhsu  @vieux  @thaJeztah 
> [18.01] Changelog for 18.01

- CHANGELOG.md
> [18.01] Update changelog

- CHANGELOG.md
Everything in the deleted section is what I would intend to delete, but I have left it there for review.
~Currently going through the `triage` section to sort it out.~ 
**Ready for review**
> [18.02] Create 18.02 Changelog

- CHANGELOG.md
> [18.02] update changelog for 18.02.0-ce-rc2

- CHANGELOG.md
Added 2 more items to the `Client` section and moved one item into that section.
> [18.02] more adjustments to changelog for 18.02.0-ce-rc2

- CHANGELOG.md
> [18.02] changelog update

- CHANGELOG.md
> [17.12] changelog update for 17.12.1 rc1

- components/engine/daemon/logger/splunk/splunk.go
- components/engine/daemon/logger/splunk/splunk_test.go
- components/engine/vendor.conf
- components/engine/vendor/github.com/google/go-cmp/LICENSE
- components/engine/vendor/github.com/google/go-cmp/README.md
- components/engine/vendor/github.com/google/go-cmp/cmp/compare.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/value/format.go
- components/engine/vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- components/engine/vendor/github.com/google/go-cmp/cmp/options.go
- components/engine/vendor/github.com/google/go-cmp/cmp/path.go
- components/engine/vendor/github.com/google/go-cmp/cmp/reporter.go
- components/engine/vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
- components/engine/vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/README.md
- components/engine/vendor/github.com/gotestyourself/gotestyourself/assert/assert.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/assert/cmp/compare.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/env/env.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/fs/file.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/fs/ops.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/internal/format/format.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/internal/source/source.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/poll/poll.go
- components/engine/vendor/github.com/gotestyourself/gotestyourself/skip/skip.go
backport of https://github.com/moby/moby/pull/36220 for 17.12
```
git checkout -b 17.12-backport-support-proxy-in-splunk-driver upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 3c4537d5b33d951237ea5e4cc123953eda7a37e7
git cherry-pick -s -S -x -Xsubtree=components/engine 7d296522f68a80d540b20753ea0648171ee12825
```
no conflicts
> [17.12] Support a proxy in splunk log driver

- components/engine/daemon/daemon_linux.go
- components/engine/daemon/daemon_linux_test.go
- components/engine/daemon/oci_linux.go
backport of https://github.com/moby/moby/pull/36107 for 17.12
```
git checkout -b 17.12-backport-cleanup_daemon_root_mount upstream/17.12
git cherry-pick -s -S -x -Xsubtree=components/engine 487c6c7e73dbb7871e80d75f176dd2a3539a2947
```
no conflicts
This is only for the case when dockerd has had to re-mount the daemon
root as shared.
> [17.12] Ensure daemon root is unmounted on shutdown

- components/cli/docs/reference/commandline/run.md
- components/cli/docs/reference/commandline/service_create.md
docs cherry-picks for 18.03; more commits can be added to this, but we can merge at any point.
- https://github.com/docker/cli/pull/900 docs: mention sctp
- https://github.com/docker/cli/pull/909 Update run.md --restart to include unless-stopped
> [18.03] docs cherry-picks

- components/engine/builder/builder.go
- components/engine/builder/dockerfile/copy.go
- components/engine/builder/dockerfile/dispatchers_test.go
- components/engine/builder/dockerfile/imagecontext.go
- components/engine/builder/dockerfile/internals.go
- components/engine/builder/dockerfile/mockbackend_test.go
- components/engine/daemon/build.go
- components/engine/integration/build/build_test.go
cherry-pick: https://github.com/moby/moby/pull/36338
@andrewhsu @dnephin 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
(cherry picked from commit 7ad41d53df94c4277574d14809211b42dca2becc)
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> [18.03] builder: fix layer lifecycle leak

- CHANGELOG.md
> [18.03] Updating Changelog for 18.03

- CHANGELOG.md
> [18.03] changelog for docker-ce 18.03.0 rc4

- CHANGELOG.md
> [18.03] Bump date for 18.03.0-ce GA

- Makefile
> [master] Change to docker fork of moby-components

- CHANGELOG.md
Changelog update to include changes brought in for RC2
> [18.04]  Changelog update

- components/engine/daemon/graphdriver/windows/windows.go
backport of https://github.com/moby/moby/pull/36728 for 18.03
```
git checkout -b 18.03-backport-LayerLeak upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 1f28844d7869609f371ab2a7881e4488a79a7e27
git push -u origin 18.03-backport-LayerLeak
```
no conflicts
> [18.03] Fix Windows layer leak when write fails

- CHANGELOG.md
> [18.03] changelog

- components/engine/libcontainerd/client_daemon.go
backport of https://github.com/moby/moby/pull/36848 for 18.03
```
git checkout -b 18.03-backport-libcontainerd_client_locking upstream/18.03
git cherry-pick -s -S -x -Xsubtree=components/engine 806700e410a1b30aa1033d71d825e57880c75298
git push -u origin 18.03-backport-libcontainerd_client_locking
```
no conflits
This unblocks the client to take other restore requests and makes sure
that a long/stuck request can't block the client forever.
> [18.03] Relax global client lock on containerd restore.

- .gitignore
> [master] Update gitignore to ignore more files

- CHANGELOG.md
> [18.09] Fix typo in changelog

- CHANGELOG.md
> [19.03] added entry to changelog

- CHANGELOG.md
Ref https://github.com/docker/docker-ce/pull/645
> Add 19.03.9 Changelog

- README.md
> readme: Add repository deprecation notice

- README.md
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> remove obsolete editions
